/**
 * Additional emoji mappings for the chat application
 * This file contains additional mappings for converting text expressions to emojis
 */

// Common user intent emoji mappings
export const userIntentEmojiMap: Record<string, string> = {
  // Greetings and farewells
  "hello": "👋",
  "hi there": "👋",
  "hey": "👋",
  "greetings": "👋",
  "good morning": "🌞",
  "good afternoon": "🌤️",
  "good evening": "🌙",
  "good night": "🌜",
  "bye": "👋",
  "goodbye": "👋",
  "see you": "👋",
  "see you later": "👋",
  "see you soon": "👋",
  "take care": "🤗",
  "farewell": "👋",
  "until next time": "⏱️",
  "catch you later": "👋",
  
  // Common reactions
  "wow": "😮",
  "omg": "😱",
  "lol": "😂",
  "haha": "😂",
  "rofl": "🤣",
  "lmao": "🤣",
  "hmm": "🤔",
  "huh": "🤨",
  "eh": "😕",
  "meh": "😒",
  "ugh": "😩",
  "yay": "🎉",
  "hooray": "🎉",
  "oops": "😬",
  "ouch": "😣",
  "yikes": "😬",
  "oof": "😵",
  "phew": "😅",
  "sheesh": "😩",
  "bruh": "🙄",
  "yup": "👍",
  "nope": "👎",
  "dang": "😤",
  "damn": "😤",
  "cool": "😎",
  "nice": "👌",
  "awesome": "🤩",
  "perfect": "💯",
  "excellent": "🏆",
  
  // Questions and curiosity
  "what": "❓",
  "when": "⏰❓",
  "where": "🗺️❓",
  "who": "👤❓",
  "why": "🤔❓",
  "how": "🛠️❓",
  "really": "😲",
  "seriously": "🧐",
  "curious": "👀",
  "interested": "🧐",
  "tell me more": "📚👀",
  "explain": "🧮",
  "wondering": "🤔",
  "confused": "😕",
  "lost": "😵",
  
  // Apologies and gratitude
  "sorry": "🙏",
  "apologize": "🙏",
  "my bad": "🙏",
  "forgive me": "🙏",
  "thanks": "🙏",
  "thank you": "🙏",
  "grateful": "🙏",
  "appreciate": "🙏",
  "much appreciated": "🙏",
  "you're welcome": "😊",
  "no problem": "👌",
  "anytime": "⏰",
  "my pleasure": "😊",
  
  // Agreement and disagreement
  "agree": "👍",
  "disagree": "👎",
  "yes": "✅",
  "no": "❌",
  "maybe": "🤷",
  "perhaps": "🤷",
  "definitely": "💯",
  "absolutely": "💯",
  "not sure": "🤔",
  "possibly": "🤔",
  "correct": "✅",
  "incorrect": "❌",
  "right": "✅",
  "wrong": "❌",
  "true": "✅",
  "false": "❌",
  "exactly": "💯",
  "precisely": "🎯",
  
  // Emotions and states
  "happy": "😊",
  "sad": "😢",
  "angry": "😠",
  "frustrated": "😤",
  "excited": "🤩",
  "bored": "😴",
  "tired": "😫",
  "sleepy": "😴",
  "hungry": "🍽️",
  "thirsty": "🥤",
  "sick": "🤒",
  "healthy": "💪",
  "stressed": "😰",
  "relaxed": "😌",
  "nervous": "😬",
  "confident": "😎",
  "proud": "🥹",
  "ashamed": "😳",
  "embarrassed": "😳",
  "surprised": "😲",
  "shocked": "😱",
  "jealous": "😒",
  "envious": "😒",
  "guilty": "😔",
  "innocent": "😇",
  "lonely": "🥺",
  "loved": "🥰",
  "hopeful": "🙏",
  "hopeless": "😞",
  "motivated": "💪",
  "lazy": "😴",
  "energetic": "⚡",
  "calm": "😌",
  "peaceful": "🕊️",
  "anxious": "😨",
  "afraid": "😨",
  "terrified": "😱",
  "overwhelmed": "😵‍💫",
  "underwhelmed": "😒",
  "satisfied": "😌",
  "unsatisfied": "😕",
  "content": "☺️",
  "discontent": "😒",
  
  // Physical actions
  "nod": "😌",
  "nodding": "😌",
  "shaking head": "😔",
  "shrugs": "🤷",
  "shrugging": "🤷",
  "points": "👉",
  "pointing": "👉",
  "claps": "👏",
  "clapping": "👏",
  "waves": "👋",
  "waving": "👋",
  "high five": "🙌",
  "fist bump": "👊",
  "thumbs up": "👍",
  "thumbs down": "👎",
  "dancing": "💃",
  "jumps": "⬆️",
  "jumping": "⬆️",
  "running": "🏃",
  "walking": "🚶",
  "sleeping": "😴",
  "eating": "🍽️",
  "drinking": "🥤",
  "writing": "✍️",
  "typing": "⌨️",
  "reading": "📖",
  "listening": "👂",
  "watching": "👀",
  "looking": "👀",
  "staring": "👁️",
  "glaring": "😠",
  "hugging": "🤗",
  "kissing": "😘",
  "sighing": "😮‍💨",
  "breathing": "🫁",
  "stretching": "🧘",
  "yawning": "🥱",
  "sneezing": "🤧",
  "coughing": "😷",
  
  // Time-related
  "now": "⏰",
  "today": "📆",
  "tomorrow": "📆➡️",
  "yesterday": "📆⬅️",
  "morning": "🌅",
  "afternoon": "🌤️",
  "evening": "🌆",
  "night": "🌃",
  "midnight": "🕛",
  "noon": "🕛",
  "weekend": "🏖️",
  "weekday": "💼",
  "monday": "📅",
  "tuesday": "📅",
  "wednesday": "📅",
  "thursday": "📅",
  "friday": "📅",
  "saturday": "📅",
  "sunday": "📅",
  "january": "❄️",
  "february": "❤️",
  "march": "🌱",
  "april": "🌧️",
  "may": "🌸",
  "june": "☀️",
  "july": "🏖️",
  "august": "☀️",
  "september": "🍂",
  "october": "🎃",
  "november": "🦃",
  "december": "🎄",
  "year": "📅",
  "month": "📅",
  "week": "📅",
  "day": "📅",
  "hour": "⏰",
  "minute": "⏱️",
  "second": "⏱️",
  "early": "⏰",
  "late": "⏰",
  "deadline": "⏳",
  "schedule": "📅",
  "calendar": "📅",
  "anniversary": "🎂",
  "birthday": "🎂",
  "holiday": "🎉",
  "vacation": "🏖️",
  
  // Weather and nature
  "sunny": "☀️",
  "cloudy": "☁️",
  "rainy": "🌧️",
  "snowy": "❄️",
  "stormy": "⛈️",
  "windy": "🌬️",
  "foggy": "🌫️",
  "hot": "🔥",
  "cold": "❄️",
  "warm": "🌡️",
  "cool": "🌡️",
  "freezing": "🥶",
  "boiling": "♨️",
  "thunder": "⚡",
  "lightning": "⚡",
  "rainbow": "🌈",
  "sunset": "🌅",
  "sunrise": "🌄",
  "stars": "✨",
  "moon": "🌙",
  "sun": "☀️",
  "cloud": "☁️",
  "rain": "🌧️",
  "snow": "❄️",
  "wind": "🌬️",
  "fog": "🌫️",
  "mountain": "⛰️",
  "beach": "🏖️",
  "ocean": "🌊",
  "sea": "🌊",
  "lake": "🏞️",
  "river": "🏞️",
  "forest": "🌲",
  "tree": "🌳",
  "flower": "🌸",
  "plant": "🌱",
  "grass": "🌿",
  "leaf": "🍃",
  "autumn": "🍂",
  "winter": "❄️",
  "spring": "🌸",
  "summer": "☀️",
  
  // Food and drink
  "hungry": "🍽️",
  "thirsty": "🥤",
  "food": "🍲",
  "meal": "🍽️",
  "breakfast": "🍳",
  "lunch": "🥪",
  "dinner": "🍲",
  "snack": "🍿",
  "dessert": "🍰",
  "coffee": "☕",
  "tea": "🍵",
  "water": "💧",
  "juice": "🧃",
  "soda": "🥤",
  "milk": "🥛",
  "beer": "🍺",
  "wine": "🍷",
  "cocktail": "🍸",
  "pizza": "🍕",
  "burger": "🍔",
  "sandwich": "🥪",
  "salad": "🥗",
  "pasta": "🍝",
  "rice": "🍚",
  "bread": "🍞",
  "cake": "🍰",
  "ice cream": "🍦",
  "chocolate": "🍫",
  "candy": "🍬",
  "fruit": "🍎",
  "vegetable": "🥦",
  "meat": "🥩",
  "chicken": "🍗",
  "fish": "🐟",
  "seafood": "🦐",
  "cheese": "🧀",
  "egg": "🥚",
  "cooking": "👨‍🍳",
  "baking": "🥖",
  "grill": "🍖",
  "fry": "🍳",
  "boil": "♨️",
  "recipe": "📝",
  "restaurant": "🍽️",
  "cafe": "☕",
  "bar": "🍸",
  
  // Technology
  "phone": "📱",
  "computer": "💻",
  "laptop": "💻",
  "desktop": "🖥️",
  "tablet": "📱",
  "keyboard": "⌨️",
  "mouse": "🖱️",
  "screen": "🖥️",
  "monitor": "🖥️",
  "internet": "🌐",
  "wifi": "📶",
  "online": "🌐",
  "offline": "🔌",
  "website": "🌐",
  "app": "📱",
  "software": "💿",
  "hardware": "🔧",
  "download": "⬇️",
  "upload": "⬆️",
  "email": "📧",
  "message": "💬",
  "text": "💬",
  "call": "📞",
  "video call": "📹",
  "camera": "📷",
  "photo": "📸",
  "video": "🎥",
  "audio": "🔊",
  "speaker": "🔊",
  "microphone": "🎙️",
  "headphones": "🎧",
  "battery": "🔋",
  "charging": "🔌",
  "power": "⚡",
  "update": "🔄",
  "upgrade": "⬆️",
  "install": "💾",
  "uninstall": "🗑️",
  "restart": "🔄",
  "reboot": "🔄",
  "login": "🔑",
  "logout": "🚪",
  "password": "🔑",
  "security": "🔒",
  "bug": "🐛",
  "error": "❌",
  "crash": "💥",
  "glitch": "⚠️",
  "coding": "👨‍💻",
  "programming": "👨‍💻",
  "developer": "👨‍💻",
  
  // Work and education
  "work": "💼",
  "job": "💼",
  "office": "🏢",
  "meeting": "👥",
  "presentation": "📊",
  "conference": "🎤",
  "interview": "🤝",
  "resume": "📄",
  "cv": "📄",
  "career": "📈",
  "business": "💼",
  "company": "🏢",
  "startup": "🚀",
  "entrepreneur": "👔",
  "boss": "👨‍💼",
  "employee": "👨‍💼",
  "coworker": "👨‍💼",
  "colleague": "👨‍💼",
  "team": "👥",
  "project": "📋",
  "deadline": "⏳",
  "task": "✅",
  "email": "📧",
  "report": "📊",
  "document": "📄",
  "file": "📁",
  "folder": "📁",
  "notes": "📝",
  "pen": "🖊️",
  "pencil": "✏️",
  "paper": "📄",
  "printer": "🖨️",
  "salary": "💰",
  "promotion": "📈",
  "raise": "💰",
  "bonus": "💰",
  "school": "🏫",
  "university": "🏫",
  "college": "🏫",
  "class": "📚",
  "course": "📚",
  "lesson": "📖",
  "lecture": "🎓",
  "homework": "📝",
  "assignment": "📝",
  "exam": "📝",
  "test": "📝",
  "grade": "🅰️",
  "graduation": "🎓",
  "degree": "🎓",
  "diploma": "📜",
  "certificate": "📜",
  "student": "👨‍🎓",
  "teacher": "👨‍🏫",
  "professor": "👨‍🏫",
  "tutor": "👨‍🏫",
  "learn": "📚",
  "study": "📚",
  "research": "🔍",
  
  // Travel and places
  "travel": "✈️",
  "trip": "🧳",
  "journey": "🧳",
  "vacation": "🏖️",
  "holiday": "🎉",
  "adventure": "🧗",
  "explore": "🧭",
  "sightseeing": "📸",
  "tourist": "📸",
  "map": "🗺️",
  "compass": "🧭",
  "destination": "📍",
  "airport": "✈️",
  "airplane": "✈️",
  "flight": "✈️",
  "train": "🚆",
  "bus": "🚌",
  "car": "🚗",
  "taxi": "🚕",
  "uber": "🚗",
  "bike": "🚲",
  "motorcycle": "🏍️",
  "walk": "🚶",
  "hike": "🥾",
  "road": "🛣️",
  "street": "🛣️",
  "highway": "🛣️",
  "bridge": "🌉",
  "hotel": "🏨",
  "motel": "🏨",
  "hostel": "🏨",
  "resort": "🏖️",
  "campsite": "⛺",
  "camping": "⛺",
  "city": "🏙️",
  "town": "🏘️",
  "village": "🏡",
  "countryside": "🌄",
  "beach": "🏖️",
  "mountain": "⛰️",
  "forest": "🌲",
  "park": "🏞️",
  "garden": "🌳",
  "zoo": "🦁",
  "museum": "🏛️",
  "gallery": "🖼️",
  "theater": "🎭",
  "cinema": "🎬",
  "restaurant": "🍽️",
  "cafe": "☕",
  "shop": "🛍️",
  "mall": "🛍️",
  "market": "🛒",
  "store": "🏪",
  "supermarket": "🛒",
  "pharmacy": "💊",
  "hospital": "🏥",
  "doctor": "👨‍⚕️",
  "clinic": "🏥",
  "dentist": "🦷",
  "gym": "💪",
  "pool": "🏊",
  "stadium": "🏟️",
  
  // Sports and activities
  "sports": "🏅",
  "game": "🎮",
  "play": "🎮",
  "exercise": "🏋️",
  "workout": "💪",
  "fitness": "💪",
  "run": "🏃",
  "running": "🏃",
  "jog": "🏃",
  "jogging": "🏃",
  "walk": "🚶",
  "walking": "🚶",
  "hike": "🥾",
  "hiking": "🥾",
  "swim": "🏊",
  "swimming": "🏊",
  "cycle": "🚴",
  "cycling": "🚴",
  "bike": "🚲",
  "biking": "🚴",
  "football": "⚽",
  "soccer": "⚽",
  "basketball": "🏀",
  "baseball": "⚾",
  "tennis": "🎾",
  "golf": "🏌️",
  "hockey": "🏒",
  "volleyball": "🏐",
  "rugby": "🏉",
  "cricket": "🏏",
  "boxing": "🥊",
  "martial arts": "🥋",
  "yoga": "🧘",
  "meditation": "🧘",
  "pilates": "🧘",
  "dance": "💃",
  "dancing": "💃",
  "ballet": "🩰",
  "skate": "⛸️",
  "skating": "⛸️",
  "ski": "⛷️",
  "skiing": "⛷️",
  "snowboard": "🏂",
  "surf": "🏄",
  "surfing": "🏄",
  "sail": "⛵",
  "sailing": "⛵",
  "climb": "🧗",
  "climbing": "🧗",
  "fish": "🎣",
  "fishing": "🎣",
  "hunt": "🏹",
  "hunting": "🏹",
  "camp": "⛺",
  "camping": "⛺",
  "picnic": "🧺",
  "barbecue": "🍖",
  "bbq": "🍖",
  "party": "🎉",
  "celebration": "🎉",
  "festival": "🎪",
  "concert": "🎵",
  "movie": "🎬",
  "theater": "🎭",
  "museum": "🏛️",
  "art": "🎨",
  "painting": "🎨",
  "drawing": "✏️",
  "photography": "📷",
  "writing": "✍️",
  "reading": "📚",
  "book": "📖",
  "novel": "📚",
  "poetry": "📝",
  "music": "🎵",
  "song": "🎵",
  "sing": "🎤",
  "singing": "🎤",
  "play instrument": "🎸",
  "guitar": "🎸",
  "piano": "🎹",
  "drums": "🥁",
  "violin": "🎻",
  "flute": "🎵",
  "trumpet": "🎺",
  "saxophone": "🎷",
  
  // Medical and health
  "health": "🏥",
  "healthcare": "⚕️",
  "medical": "⚕️",
  "doctor": "👨‍⚕️",
  "nurse": "👩‍⚕️",
  "hospital": "🏥",
  "clinic": "🏥",
  "appointment": "📅",
  "checkup": "👨‍⚕️",
  "medicine": "💊",
  "medication": "💊",
  "pill": "💊",
  "drug": "💊",
  "prescription": "📝",
  "pharmacy": "💊",
  "treatment": "💉",
  "therapy": "🧠",
  "surgery": "🔪",
  "operation": "🔪",
  "emergency": "🚑",
  "ambulance": "🚑",
  "injury": "🤕",
  "hurt": "🤕",
  "pain": "😣",
  "ache": "😣",
  "sore": "😣",
  "headache": "🤕",
  "stomachache": "😣",
  "fever": "🤒",
  "cold": "🤧",
  "flu": "🤒",
  "virus": "🦠",
  "disease": "🦠",
  "infection": "🦠",
  "covid": "😷",
  "coronavirus": "🦠",
  "mask": "😷",
  "vaccine": "💉",
  "vaccination": "💉",
  "shot": "💉",
  "injection": "💉",
  "blood": "🩸",
  "test": "🔬",
  "scan": "🔬",
  "xray": "🦴",
  "bandage": "🩹",
  "cast": "🦴",
  "crutches": "🦯",
  "wheelchair": "♿",
  "healthy": "💪",
  "fit": "💪",
  "wellness": "🧘",
  "diet": "🥗",
  "nutrition": "🥗",
  "vitamin": "💊",
  "supplement": "💊",
  "exercise": "🏋️",
  "workout": "💪",
  "fitness": "💪",
  "weight": "⚖️",
  "fat": "🍔",
  "thin": "🥢",
  "sleep": "😴",
  "insomnia": "😫",
  "rest": "💤",
  "mental health": "🧠",
  "depression": "😔",
  "anxiety": "😰",
  "stress": "😰",
  "therapy": "🛋️",
  "counseling": "👥",
  "psychologist": "👨‍⚕️",
  "psychiatrist": "👨‍⚕️",
  "therapist": "👨‍⚕️",
  
  // Events and celebrations
  "event": "📅",
  "celebration": "🎉",
  "party": "🎉",
  "birthday": "🎂",
  "anniversary": "💍",
  "wedding": "💒",
  "engagement": "💍",
  "graduation": "🎓",
  "promotion": "📈",
  "retirement": "🏖️",
  "baby shower": "👶",
  "bridal shower": "👰",
  "bachelor party": "🕺",
  "bachelorette party": "💃",
  "funeral": "⚰️",
  "memorial": "🕯️",
  "holiday": "🎄",
  "christmas": "🎄",
  "halloween": "🎃",
  "thanksgiving": "🦃",
  "easter": "🐰",
  "valentine's day": "❤️",
  "new year": "🎆",
  "new year's eve": "🎆",
  "new year's day": "🎆",
  "independence day": "🎆",
  "july 4th": "🎆",
  "memorial day": "🇺🇸",
  "labor day": "👷",
  "veterans day": "🎖️",
  "st. patrick's day": "☘️",
  "cinco de mayo": "🌮",
  "mother's day": "👩",
  "father's day": "👨",
  "festival": "🎪",
  "concert": "🎵",
  "show": "🎭",
  "performance": "🎭",
  "exhibition": "🖼️",
  "fair": "🎪",
  "carnival": "🎪",
  "parade": "🎭",
  "ceremony": "🏆",
  "award": "🏆",
  "prize": "🏆",
  "present": "🎁",
  "gift": "🎁",
  "surprise": "🎁",
  "cake": "🎂",
  "candle": "🕯️",
  "balloon": "🎈",
  "confetti": "🎊",
  "fireworks": "🎆",
  "invitation": "📨",
  "rsvp": "📨",
  "guest": "👥",
  "host": "🏠",
  "dress up": "👗",
  "costume": "🎭",
  "decorate": "🎨",
  "decoration": "🎊",
  
  // Family and relationships
  "family": "👪",
  "relative": "👪",
  "parent": "👪",
  "mother": "👩",
  "mom": "👩",
  "father": "👨",
  "dad": "👨",
  "brother": "👦",
  "sister": "👧",
  "sibling": "👦👧",
  "son": "👦",
  "daughter": "👧",
  "child": "👶",
  "baby": "👶",
  "infant": "👶",
  "toddler": "🧒",
  "kid": "🧒",
  "teenager": "🧑",
  "teen": "🧑",
  "adult": "🧑",
  "grandparent": "👴👵",
  "grandmother": "👵",
  "grandma": "👵",
  "grandfather": "👴",
  "grandpa": "👴",
  "grandchild": "👶",
  "grandson": "👦",
  "granddaughter": "👧",
  "uncle": "🧔",
  "aunt": "👩",
  "cousin": "🧑",
  "nephew": "👦",
  "niece": "👧",
  "spouse": "💑",
  "husband": "👨",
  "wife": "👩",
  "partner": "💑",
  "fiancé": "💍",
  "fiancée": "💍",
  "boyfriend": "👨",
  "girlfriend": "👩",
  "couple": "💑",
  "relationship": "❤️",
  "date": "💘",
  "dating": "💘",
  "crush": "💘",
  "love": "❤️",
  "lover": "❤️",
  "friend": "👫",
  "bestie": "👯",
  "best friend": "👯",
  "bff": "👯",
  "friendship": "👫",
  "buddy": "👫",
  "pal": "👫",
  "acquaintance": "🤝",
  "colleague": "👔",
  "coworker": "👔",
  "neighbor": "🏡",
  "roommate": "🏠",
  "classmate": "🏫",
  "team": "👥",
  "group": "👥",
  "community": "🏙️",
  "society": "🏙️",
  "tribe": "👥",
  "clan": "👥",
  
  // Transportation and movement
  "car": "🚗",
  "automobile": "🚗",
  "vehicle": "🚗",
  "truck": "🚚",
  "bus": "🚌",
  "van": "🚐",
  "taxi": "🚕",
  "uber": "🚗",
  "lyft": "🚗",
  "motorcycle": "🏍️",
  "bike": "🚲",
  "bicycle": "🚲",
  "scooter": "🛴",
  "skateboard": "🛹",
  "train": "🚆",
  "subway": "🚇",
  "metro": "🚇",
  "tram": "🚃",
  "rail": "🚆",
  "boat": "⛵",
  "ship": "🚢",
  "ferry": "⛴️",
  "cruise": "🚢",
  "airplane": "✈️",
  "plane": "✈️",
  "flight": "✈️",
  "helicopter": "🚁",
  "rocket": "🚀",
  "spaceship": "🚀",
  "drive": "🚗",
  "ride": "🚗",
  "fly": "✈️",
  "sail": "⛵",
  "travel": "✈️",
  "commute": "🚉",
  "journey": "🧳",
  "trip": "🧳",
  "vacation": "🏖️",
  "road": "🛣️",
  "street": "🛣️",
  "highway": "🛣️",
  "intersection": "🚦",
  "traffic": "🚦",
  "traffic light": "🚦",
  "stop sign": "🛑",
  "parking": "🅿️",
  "gas station": "⛽",
  "petrol station": "⛽",
  "charging station": "🔌",
  "airport": "✈️",
  "terminal": "🏢",
  "gate": "🚪",
  "security": "👮",
  "customs": "🛃",
  "passport": "📕",
  "visa": "📄",
  "ticket": "🎫",
  "boarding pass": "🎫",
  "reservation": "📑",
  "luggage": "🧳",
  "suitcase": "🧳",
  "backpack": "🎒",
  "bag": "👜",
  "map": "🗺️",
  "gps": "📍",
  "navigation": "🧭",
  "compass": "🧭",
  "direction": "↔️",
  "north": "⬆️",
  "south": "⬇️",
  "east": "➡️",
  "west": "⬅️",
  "left": "⬅️",
  "right": "➡️",
  "up": "⬆️",
  "down": "⬇️",
  "forward": "⏩",
  "backward": "⏪",
  
  // Money and shopping
  "money": "💰",
  "cash": "💵",
  "coin": "🪙",
  "dollar": "💵",
  "euro": "💶",
  "pound": "💷",
  "yen": "💴",
  "currency": "💱",
  "exchange": "💱",
  "bank": "🏦",
  "atm": "🏧",
  "credit card": "💳",
  "debit card": "💳",
  "card": "💳",
  "bill": "💰",
  "payment": "💰",
  "pay": "💰",
  "loan": "💰",
  "debt": "💰",
  "mortgage": "🏠",
  "rent": "🏠",
  "save": "💰",
  "savings": "💰",
  "invest": "📈",
  "investment": "📈",
  "stock": "📈",
  "bond": "📈",
  "fund": "💰",
  "budget": "💰",
  "expense": "💰",
  "receipt": "🧾",
  "sale": "💸",
  "discount": "🏷️",
  "coupon": "🏷️",
  "offer": "💰",
  "deal": "🤝",
  "free": "🆓",
  "cheap": "💰",
  "expensive": "💰",
  "price": "💲",
  "cost": "💲",
  "value": "💲",
  "worth": "💲",
  "wealthy": "💰",
  "rich": "💰",
  "poor": "💰",
  "broke": "💰",
  "shop": "🛍️",
  "shopping": "🛍️",
  "store": "🏪",
  "mall": "🛍️",
  "market": "🛒",
  "supermarket": "🛒",
  "grocery": "🛒",
  "buy": "🛍️",
  "purchase": "🛍️",
  "sell": "💰",
  "auction": "🔨",
  "bid": "🔨",
  "retail": "👕",
  "wholesale": "📦",
  "online shopping": "🛍️",
  "ecommerce": "🛍️",
  "amazon": "📦",
  "ebay": "🛍️",
  "etsy": "🛍️",
  "cart": "🛒",
  "basket": "🧺",
  "checkout": "💳",
  "order": "📦",
  "shipping": "📦",
  "delivery": "📦",
  "return": "↩️",
  "refund": "💰",
  "warranty": "📃",
  "item": "📦",
  "product": "📦",
  "merchandise": "👕",
  "goods": "📦",
  "gift": "🎁",
  "present": "🎁",
  
  // Countries and flags
  "country": "🌎",
  "nation": "🌎",
  "international": "🌎",
  "global": "🌎",
  "world": "🌎",
  "usa": "🇺🇸",
  "america": "🇺🇸",
  "united states": "🇺🇸",
  "canada": "🇨🇦",
  "mexico": "🇲🇽",
  "uk": "🇬🇧",
  "united kingdom": "🇬🇧",
  "england": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "ireland": "🇮🇪",
  "france": "🇫🇷",
  "germany": "🇩🇪",
  "italy": "🇮🇹",
  "spain": "🇪🇸",
  "portugal": "🇵🇹",
  "greece": "🇬🇷",
  "russia": "🇷🇺",
  "china": "🇨🇳",
  "japan": "🇯🇵",
  "korea": "🇰🇷",
  "south korea": "🇰🇷",
  "north korea": "🇰🇵",
  "india": "🇮🇳",
  "australia": "🇦🇺",
  "new zealand": "🇳🇿",
  "brazil": "🇧🇷",
  "argentina": "🇦🇷",
  "chile": "🇨🇱",
  "peru": "🇵🇪",
  "colombia": "🇨🇴",
  "venezuela": "🇻🇪",
  "egypt": "🇪🇬",
  "south africa": "🇿🇦",
  "nigeria": "🇳🇬",
  "kenya": "🇰🇪",
  "morocco": "🇲🇦",
  "saudi arabia": "🇸🇦",
  "israel": "🇮🇱",
  "turkey": "🇹🇷",
  "ukraine": "🇺🇦",
  "sweden": "🇸🇪",
  "norway": "🇳🇴",
  "denmark": "🇩🇰",
  "finland": "🇫🇮",
  "iceland": "🇮🇸",
  "switzerland": "🇨🇭",
  "austria": "🇦🇹",
  "belgium": "🇧🇪",
  "netherlands": "🇳🇱",
  "poland": "🇵🇱",
  "czech republic": "🇨🇿",
  "hungary": "🇭🇺",
  "romania": "🇷🇴",
  "bulgaria": "🇧🇬",
  "serbia": "🇷🇸",
  "croatia": "🇭🇷",
  "slovenia": "🇸🇮",
  "slovakia": "🇸🇰",
  "estonia": "🇪🇪",
  "latvia": "🇱🇻",
  "lithuania": "🇱🇹",
  "belarus": "🇧🇾",
  "moldova": "🇲🇩",
  "asia": "🌏",
  "europe": "🌍",
  "north america": "🌎",
  "south america": "🌎",
  "africa": "🌍",
  "oceania": "🌏",
  "antarctica": "🇦🇶",
  
  // Animals and nature
  "animal": "🐾",
  "pet": "🐾",
  "dog": "🐕",
  "cat": "🐈",
  "bird": "🐦",
  "fish": "🐟",
  "turtle": "🐢",
  "rabbit": "🐇",
  "hamster": "🐹",
  "guinea pig": "🐹",
  "horse": "🐎",
  "cow": "🐄",
  "pig": "🐖",
  "sheep": "🐑",
  "goat": "🐐",
  "chicken": "🐔",
  "rooster": "🐓",
  "duck": "🦆",
  "goose": "🦢",
  "turkey": "🦃",
  "dove": "🕊️",
  "eagle": "🦅",
  "owl": "🦉",
  "bat": "🦇",
  "wolf": "🐺",
  "fox": "🦊",
  "bear": "🐻",
  "panda": "🐼",
  "koala": "🐨",
  "tiger": "🐯",
  "lion": "🦁",
  "leopard": "🐆",
  "horse": "🐎",
  "unicorn": "🦄",
  "zebra": "🦓",
  "deer": "🦌",
  "camel": "🐪",
  "giraffe": "🦒",
  "elephant": "🐘",
  "rhinoceros": "🦏",
  "hippopotamus": "🦛",
  "mouse": "🐁",
  "rat": "🐀",
  "chipmunk": "🐿️",
  "hedgehog": "🦔",
  "raccoon": "🦝",
  "sloth": "🦥",
  "otter": "🦦",
  "skunk": "🦨",
  "kangaroo": "🦘",
  "monkey": "🐒",
  "gorilla": "🦍",
  "orangutan": "🦧",
  "frog": "🐸",
  "crocodile": "🐊",
  "turtle": "🐢",
  "lizard": "🦎",
  "snake": "🐍",
  "dragon": "🐉",
  "dinosaur": "🦖",
  "t-rex": "🦖",
  "sauropod": "🦕",
  "fish": "🐟",
  "tropical fish": "🐠",
  "blowfish": "🐡",
  "shark": "🦈",
  "octopus": "🐙",
  "shell": "🐚",
  "snail": "🐌",
  "butterfly": "🦋",
  "bug": "🐛",
  "ant": "🐜",
  "honeybee": "🐝",
  "ladybug": "🐞",
  "cricket": "🦗",
  "cockroach": "🪳",
  "spider": "🕷️",
  "scorpion": "🦂",
  "mosquito": "🦟",
  "fly": "🪰",
  "worm": "🪱",
  "microbe": "🦠",
  "plant": "🌱",
  "tree": "🌳",
  "evergreen tree": "🌲",
  "palm tree": "🌴",
  "cactus": "🌵",
  "shamrock": "☘️",
  "four leaf clover": "🍀",
  "flower": "🌸",
  "rose": "🌹",
  "tulip": "🌷",
  "blossom": "🌼",
  "sunflower": "🌻",
  "herb": "🌿",
  "mushroom": "🍄",
  "nature": "🌿",
  "environment": "🌿",
  "earth": "🌎",
  "globe": "🌎",
  "mountain": "⛰️",
  "volcano": "🌋",
  "desert": "🏜️",
  "island": "🏝️",
  "beach": "🏖️",
  "national park": "🏞️",
  
  // Other common expressions
  "okay": "👌",
  "ok": "👌",
  "yep": "👍",
  "nah": "👎",
  "good": "👍",
  "great": "👍",
  "bad": "👎",
  "terrible": "👎",
  "help": "🆘",
  "wait": "⏳",
  "hurry": "⏱️",
  "slow": "🐢",
  "fast": "⚡",
  "stop": "🛑",
  "go": "🚦",
  "start": "▶️",
  "end": "🏁",
  "win": "🏆",
  "lose": "😢",
  "tie": "🤝",
  "try": "🔄",
  "done": "✅",
  "complete": "✅",
  "incomplete": "❌",
  "success": "🎉",
  "failure": "❌",
  "lucky": "🍀",
  "unlucky": "🤦",
  "careful": "⚠️",
  "danger": "⚠️",
  "warning": "⚠️",
  "emergency": "🚨",
  "fire": "🔥",
  "water": "💧",
  "smoke": "💨",
  "fix": "🔧",
  "repair": "🔧",
  "break": "💔",
  "broken": "💔",
  "magic": "✨",
  "sparkle": "✨",
  "star": "⭐",
  "wish": "🌠",
  "pray": "🙏",
  "hope": "🤞",
  "dream": "💤",
  "nightmare": "😱",
  "secret": "🤫",
  "quiet": "🤫",
  "loud": "📢",
  "noise": "🔊",
  "music": "🎵",
  "dance": "💃",
  "sing": "🎤",
  "art": "🎨",
  "science": "🔬",
  "math": "🔢",
  "history": "📜",
  "language": "🗣️",
  "speak": "🗣️",
  "talk": "🗣️",
  "listen": "👂",
  "hear": "👂",
  "see": "👀",
  "look": "👀",
  "watch": "👀",
  "touch": "👈",
  "feel": "❤️",
  "taste": "👅",
  "smell": "👃",
  "sense": "🧠",
  "think": "🧠",
  "thought": "💭",
  "idea": "💡",
  "smart": "🧠",
  "intelligent": "🧠",
  "genius": "🧠",
  "stupid": "🤦",
  "silly": "🤪",
  "crazy": "🤪",
  "wild": "🤪",
  "calm": "😌",
  "peace": "☮️",
  "war": "⚔️",
  "fight": "👊",
  "attack": "👊",
  "defend": "🛡️",
  "protect": "🛡️",
  "save": "💾",
  "delete": "🗑️",
  "search": "🔍",
  "find": "🔍",
  "hide": "🙈",
  "seek": "👀",
  "open": "📂",
  "close": "📁",
  "lock": "🔒",
  "unlock": "🔓",
  "key": "🔑",
  "password": "🔑",
  "enter": "↩️",
  "exit": "🚪",
  "join": "🤝",
  "leave": "👋",
  "welcome": "🤗",
  "goodbye": "👋",
  "privacy": "🔒",
  "security": "🔒",
  "safe": "🔒",
  "unsafe": "⚠️",
  "new": "🆕",
  "old": "👴",
  "young": "👶",
  "fresh": "✨",
  "stale": "🥴",
  "clean": "✨",
  "dirty": "🧹",
  "wash": "🧼",
  "dry": "☀️",
  "wet": "💧",
  "hot": "🔥",
  "cold": "❄️",
  "warm": "☀️",
  "cool": "🥶",
  "high": "⬆️",
  "low": "⬇️",
  "tall": "↕️",
  "short": "↕️",
  "big": "📏",
  "small": "📏",
  "large": "📏",
  "tiny": "📏",
  "huge": "📏",
  "wide": "📏",
  "narrow": "📏",
  "thick": "📏",
  "thin": "📏",
  "deep": "📏",
  "shallow": "📏",
  "full": "🈵",
  "empty": "📭",
  "half": "½",
  "quarter": "¼",
  "whole": "⭕",
  "part": "🧩",
  "piece": "🧩",
  "sharp": "📌",
  "blunt": "🥄",
  "soft": "🧸",
  "hard": "🪨",
  "flat": "📄",
  "round": "⭕",
  "square": "⬜",
  "circle": "⭕",
  "triangle": "🔺",
  "rectangle": "⬜",
  "star": "⭐",
  "heart": "❤️",
  "diamond": "💎",
  "spade": "♠️",
  "club": "♣️",
  "cross": "✝️",
  "infinity": "♾️",
  "spiral": "🌀",
  "rainbow": "🌈",
  "sparkle": "✨",
  "glitter": "✨",
  "shine": "✨",
  "glow": "✨",
  "dark": "🌑",
  "light": "💡",
  "bright": "💡",
  "dim": "🔅",
  "black": "⚫",
  "white": "⚪",
  "red": "🔴",
  "orange": "🟠",
  "yellow": "🟡",
  "green": "🟢",
  "blue": "🔵",
  "purple": "🟣",
  "pink": "🎀",
  "brown": "🟤",
  "gray": "⚪",
  "gold": "🥇",
  "silver": "🥈",
  "bronze": "🥉",
  "metal": "🪨",
  "wood": "🪵",
  "glass": "🥂",
  "plastic": "🧫",
  "paper": "📄",
  "stone": "🪨",
  "rock": "🪨",
  "sand": "🏝️",
  "water": "💧",
  "fire": "🔥",
  "earth": "🪨",
  "air": "💨",
  "wind": "🌬️",
  "sunny": "☀️",
  "cloudy": "☁️",
  "rainy": "🌧️",
  "snowy": "❄️",
  "foggy": "🌫️",
  "stormy": "⛈️",
  "thunder": "⚡",
  "lightning": "⚡",
  "rainbow": "🌈",
  "moonlight": "🌙",
  "starry": "✨",
  "space": "🌌",
  "galaxy": "🌌",
  "universe": "🌌",
  "alien": "👽",
  "ufo": "🛸",
  "robot": "🤖",
  "ghost": "👻",
  "monster": "👹",
  "vampire": "🧛",
  "werewolf": "🐺",
  "zombie": "🧟",
  "fairy": "🧚",
  "mermaid": "🧜",
  "unicorn": "🦄",
  "dragon": "🐉",
  "wizard": "🧙",
  "witch": "🧙‍♀️",
  "magic": "✨",
  "superhero": "🦸",
  "villain": "🦹",
  "angel": "👼",
  "devil": "😈"
};

// Export combined mappings
export const additionalEmojiMap: Record<string, string> = {
  ...userIntentEmojiMap
};