/**
 * Character-specific emoji mappings for the chat application
 * This file contains mappings for converting character expressions and actions to emojis
 */

// Character facial expressions
export const characterFacialEmojiMap: Record<string, string> = {
  // Basic facial expressions
  "smiles": "😊",
  "smiles warmly": "🥰",
  "smiles softly": "😊",
  "smiles brightly": "😁",
  "smiles widely": "😀",
  "beams": "😁",
  "beams happily": "😄",
  "grins": "😁",
  "grins widely": "😀",
  "grins mischievously": "😏",
  "smirks": "😏",
  "smirks playfully": "😼",
  "winks": "😉",
  "winks playfully": "😉",
  "laughs": "😂",
  "laughs softly": "😄",
  "laughs nervously": "😅",
  "laughs heartily": "🤣",
  "chuckles": "😄",
  "chuckles softly": "😊",
  "giggles": "🤭",
  "giggles softly": "🤭",
  "grins cheekily": "😏",
  "guffaws": "😂",
  "snickers": "😏",
  "frowns": "😠",
  "frowns slightly": "🙁",
  "frowns deeply": "😡",
  "scowls": "😠",
  "pouts": "😡",
  "pouts cutely": "🥺",
  "sulks": "😒",
  "glares": "😠",
  "glares angrily": "😡",
  "glowers": "😠",
  "grimaces": "😬",
  "winces": "😬",
  "cringes": "😬",
  "scrunches nose": "😖",
  "wrinkles nose": "😖",
  "squints": "😑",
  "squints suspiciously": "🤨",
  "narrows eyes": "😒",
  "widens eyes": "👀",
  "raises eyebrows": "🤨",
  "arches eyebrow": "🤨",
  "raises an eyebrow": "🤨",
  "furrows brow": "😟",
  "knits brow": "😟",
  "looks surprised": "😮",
  "looks shocked": "😱",
  "looks confused": "😕",
  "looks puzzled": "🤔",
  "looks thoughtful": "🤔",
  "looks concerned": "😟",
  "looks worried": "😟",
  "looks anxious": "😰",
  "looks nervous": "😬",
  "looks fearful": "😨",
  "looks terrified": "😱",
  "looks scared": "😨",
  "looks sad": "😢",
  "looks upset": "😢",
  "looks disappointed": "😞",
  "looks dejected": "😞",
  "looks annoyed": "😒",
  "looks irritated": "😒",
  "looks angry": "😠",
  "looks furious": "😡",
  "looks happy": "😊",
  "looks pleased": "😊",
  "looks delighted": "😊",
  "looks excited": "😃",
  "looks eager": "😃",
  "looks amused": "😏",
  "looks intrigued": "🤔",
  "looks impressed": "😮",
  "looks stunned": "😮",
  "looks skeptical": "🤨",
  "looks dubious": "🤨",
  "looks doubtful": "🤨",
  "looks suspicious": "🤨",
  "looks disbelieving": "😑",
  "looks pensive": "🤔",
  "looks contemplative": "🤔",
  "looks thoughtful": "🤔",
  "looks distracted": "😶",
  "looks distant": "😶",
  "looks bored": "😒",
  "looks tired": "😴",
  "looks exhausted": "😫",
  "looks sleepy": "😴",
  "yawns": "🥱",
  "sighs": "😮‍💨",
  "sighs deeply": "😮‍💨",
  "sighs heavily": "😮‍💨",
  "sighs softly": "😮‍💨",
  "sighs contentedly": "😌",
  "sighs wearily": "😮‍💨",
  "sighs exasperatedly": "😮‍💨",
  "gapes": "😮",
  "gasps": "😲",
  "gasps softly": "😲",
  "gasps loudly": "😱",
  "gawks": "😮",
  "stares": "👀",
  "stares blankly": "😶",
  "stares intently": "👀",
  "stares curiously": "👀",
  "stares suspiciously": "🤨",
  "stares angrily": "😠",
  "stares sadly": "😢",
  "stares happily": "😊",
  "stares dreamily": "😊",
  "gazes": "👀",
  "gazes softly": "😊",
  "gazes intently": "👀",
  "gazes longingly": "😍",
  "gazes adoringly": "😍",
  "glances": "👀",
  "glances nervously": "😬",
  "glances quickly": "👀",
  "glances sideways": "👀",
  "peers": "👀",
  "peers curiously": "👀",
  "peers suspiciously": "🤨",
  "blinks": "👁️",
  "blinks rapidly": "👁️",
  "blinks slowly": "👁️",
  "blinks innocently": "😇",
  "blinks confusedly": "😕",
  "rolls eyes": "🙄",
  "averts eyes": "😔",
  "averts gaze": "😔",
  "lowers eyes": "😔",
  "lowers gaze": "😔",
  "tears up": "🥹",
  "eyes water": "🥹",
  "cries": "😢",
  "cries softly": "😢",
  "cries silently": "😢",
  "sobs": "😭",
  "sobs quietly": "😭",
  "sobs uncontrollably": "😭",
  "weeps": "😭",
  "sniffles": "😢",
  "chokes up": "😢",
  "wipes tears": "😢",
  "beams with joy": "🥰",
  "looks lovingly": "😍",
  "blushes": "😊",
  "blushes slightly": "😊",
  "blushes deeply": "😳",
  "blushes furiously": "😳",
  "flushes": "😳",
  "flushes with embarrassment": "😳",
  "pales": "😰",
  "face falls": "😞",
  "face lights up": "😊",
  "brightens": "😊",
  
  // Eye expressions
  "eyes widen": "👀",
  "eyes narrow": "😑",
  "eyes sparkle": "✨",
  "eyes gleam": "✨",
  "eyes twinkle": "✨",
  "eyes shine": "✨",
  "eyes dart": "👀",
  "eyes flicker": "👀",
  "eyes soften": "🥺",
  "eyes harden": "😠",
  "eyes tear up": "🥹",
  "eyes well up": "🥹",
  "eyes roll": "🙄",
  "eyes close": "😌",
  "eyes open wide": "😳",
  "eyes flash": "👀",
  "eyes light up": "😊",
  "giving puppy eyes": "🥺",
  "giving doe eyes": "🥺",
  "giving sad eyes": "🥺",
  "giving pleading eyes": "🥺",
  "staring intently": "👀",
  "staring longingly": "😍",
  "staring lovingly": "😍",
  "staring angrily": "😠",
  "staring suspiciously": "🤨",
  "staring curiously": "👀",
  "staring sadly": "😢",
  "staring happily": "😊",
  "staring blankly": "😶",
  "staring intensely": "👀",
  "staring dreamily": "😊",
  "staring adoringly": "😍",
  "staring coldly": "😑",
  "staring warmly": "😊",
  "staring thoughtfully": "🤔",
  "staring contemplatively": "🤔",
  "looking at you": "👀",
  "looking away": "😔",
  "looking down": "😔",
  "looking up": "😌",
  "looking around": "👀",
  "looking nervously": "😬",
  "looking anxiously": "😰",
  "looking fearfully": "😨",
  "looking hopefully": "🙏",
  "looking helplessly": "😩",
  "looking imploringly": "🥺",
  "looking pleadingly": "🥺",
  "looking beseechingly": "🥺",
  "looking apologetically": "😔",
  "looking gratefully": "😊",
  "looking sweetly": "😊",
  "looking innocently": "😇",
  "looking guiltily": "😳",
  "looking shyly": "😊",
  "looking boldly": "😏",
  "looking confidently": "😎",
  
  // Mouth expressions
  "smiles softly": "😊",
  "smiles warmly": "😊",
  "smiles brightly": "😄",
  "smiles widely": "😀",
  "smiles sweetly": "🥰",
  "smiles tenderly": "🥰",
  "smiles sadly": "😔",
  "smiles nervously": "😅",
  "smiles shyly": "😊",
  "smiles crookedly": "😏",
  "smiles awkwardly": "😅",
  "lips curl up": "😊",
  "lips twitch": "😏",
  "lips tremble": "😢",
  "lips quiver": "😢",
  "lips part": "😮",
  "lips purse": "😑",
  "lips press together": "😑",
  "lips thin": "😑",
  "lips tighten": "😑",
  "presses lips together": "😑",
  "bites lip": "😬",
  "bites lower lip": "😬",
  "chews lip": "😬",
  "licks lips": "😋",
  "mouths silently": "😶",
  "mouth waters": "🤤",
  "jaw drops": "😮",
  "jaw clenches": "😠",
  "grits teeth": "😬",
  "clenches teeth": "😬",

  // Combined facial expressions
  "face softens": "😊",
  "face hardens": "😠",
  "face falls": "😞",
  "face lights up": "😊",
  "face flushes": "😳",
  "face pales": "😨",
  "expression darkens": "😠",
  "expression softens": "😊",
  "expression brightens": "😊",
  "expression hardens": "😠",
  "expression falls": "😞",
  "expression lightens": "😊",
  "looks horrified": "😱",
  "looks mortified": "😳",
  "looks terrified": "😱",
  "looks petrified": "😱",
  "looks enthralled": "😍",
  "looks captivated": "😍",
  "looks enchanted": "😍",
  "looks mesmerized": "😍",
  "looks thrilled": "🤩",
  "looks elated": "🤩",
  "looks ecstatic": "🤩",
  "looks overjoyed": "🤩",
  "looks relieved": "😌",
  "looks content": "😌",
  "looks satisfied": "😌",
  "looks serene": "😌",
  "looks peaceful": "😌",
  "looks tranquil": "😌",
  "looks calm": "😌",
  "looks relaxed": "😌",
  "looks tense": "😬",
  "looks nervous": "😬",
  "looks anxious": "😰",
  "looks apprehensive": "😰",
  "looks concerned": "😟",
  "looks worried": "😟",
  "looks troubled": "😟",
  "looks distressed": "😟",
  "looks anguished": "😩",
  "looks pained": "😩",
  "looks tormented": "😩",
  "looks conflicted": "😣",
  "looks torn": "😣",
  "looks uncertain": "😕",
  "looks hesitant": "😕",
  "looks dubious": "🤨",
  "looks skeptical": "🤨",
  "looks cynical": "🤨",
  "looks distrusting": "🤨",
  "looks mistrustful": "🤨",
  "looks suspicious": "🤨",
  "looks wary": "🤨",
  "looks cautious": "🤨",
  "looks guarded": "🤨",
  "looks reserved": "😐",
  "looks distant": "😶",
  "looks detached": "😶",
  "looks vacant": "😶",
  "looks empty": "😶",
  "looks hollow": "😶",
};

// Character physical actions and gestures
export const characterActionEmojiMap: Record<string, string> = {
  // Head movements
  "nods": "🙂",
  "nods slowly": "🙂",
  "nods quickly": "🙂",
  "nods eagerly": "🙂",
  "nods enthusiastically": "🙂",
  "nods reluctantly": "🙂",
  "nods hesitantly": "🙂",
  "nods vigorously": "🙂",
  "shakes head": "😔",
  "shakes head slowly": "😔",
  "shakes head quickly": "😔",
  "shakes head vigorously": "😔",
  "tilts head": "🙃",
  "tilts head slightly": "🙃",
  "tilts head curiously": "🙃",
  "tilts head questioningly": "🙃",
  "tilts head thoughtfully": "🙃",
  "cocks head": "🙃",
  "turns head": "👀",
  "turns head away": "👀",
  "turns head to the side": "👀",
  "hangs head": "😔",
  "hangs head low": "😔",
  "hangs head in shame": "😔",
  "lifts chin": "😌",
  "lifts head": "😌",
  "ducks head": "🙇",
  "lowers head": "🙇",
  "looks up": "⬆️",
  "looks down": "⬇️",
  "looks away": "↗️",
  "looks back": "↩️",
  
  // Hand gestures
  "waves": "👋",
  "waves hand": "👋",
  "waves hello": "👋",
  "waves goodbye": "👋",
  "waves excitedly": "👋",
  "waves frantically": "👋",
  "waves dismissively": "👋",
  "waves wildly": "👋",
  "gestures": "👐",
  "gestures broadly": "👐",
  "gestures wildly": "👐",
  "gestures vaguely": "👐",
  "gestures excitedly": "👐",
  "gestures animatedly": "👐",
  "gestures frantically": "👐",
  "points": "👉",
  "points at": "👉",
  "points to": "👉",
  "points up": "☝️",
  "points down": "👇",
  "beckons": "👋",
  "beckons over": "👋",
  "gives thumbs up": "👍",
  "gives thumbs down": "👎",
  "raises hand": "✋",
  "raises hands": "🙌",
  "raises arms": "🙌",
  "extends hand": "✋",
  "extends hands": "🙌",
  "extends arms": "🙌",
  "offers hand": "🤝",
  "offers hands": "🙌",
  "shakes hands": "🤝",
  "holds hands": "🤝",
  "clasps hands": "🙏",
  "clasps hands together": "🙏",
  "rubs hands": "🙏",
  "rubs hands together": "🙏",
  "cracks knuckles": "👊",
  "wrings hands": "🙏",
  "clenches fists": "👊",
  "clenches hands": "👊",
  "clenches jaw": "😠",
  "opens hands": "👐",
  "opens arms": "🤗",
  "spreads arms": "🤗",
  "spreads hands": "👐",
  "crosses arms": "🙅",
  "folds arms": "🙅",
  "places hands on hips": "💁",
  "puts hands on hips": "💁",
  "high fives": "🙌",
  "fist bumps": "👊",
  "pounds fist": "👊",
  "slaps hand": "👏",
  "claps": "👏",
  "claps hands": "👏",
  "claps excitedly": "👏",
  "applauds": "👏",
  "snaps fingers": "👌",
  "wags finger": "👆",
  "shakes finger": "👆",
  "curls fingers": "👋",
  "flexes fingers": "👋",
  "wiggles fingers": "👋",
  "drums fingers": "👋",
  "taps fingers": "👋",
  "plays with fingers": "👋",
  "fidgets with hands": "👋",
  "shows palms": "🖐️",
  "opens palm": "🖐️",
  "raises palm": "🖐️",
  "raises palms": "🖐️",
  "flips hand": "👋",
  "flicks wrist": "👋",
  "rolls wrist": "👋",
  "rotates wrist": "👋",
  "flicks hand": "👋",
  "waves hand dismissively": "👋",
  "waves away": "👋",
  "pushes hand away": "👋",
  "swats hand": "👋",
  "reaches out": "🤲",
  "reaches for": "🤲",
  "grasps": "👊",
  "grabs": "👊",
  "clutches": "👊",
  "squeezes": "👊",
  "releases": "👐",
  "lets go": "👐",
  "drops": "👇",
  "picks up": "👆",
  "holds up": "👆",
  "lifts up": "👆",
  "raises up": "👆",
  "lowers": "👇",
  "puts down": "👇",
  "sets down": "👇",
  "places down": "👇",
  "tosses": "🤾",
  "throws": "🤾",
  "catches": "🙌",
  "juggles": "🤹",
  "spins": "🔄",
  "twirls": "🔄",
  "rubs eyes": "👁️",
  "wipes eyes": "👁️",
  "covers eyes": "🙈",
  "covers face": "🙈",
  "hides face": "🙈",
  "shields eyes": "🙈",
  "shields face": "🙈",
  "rubs temples": "🧠",
  "massages temples": "🧠",
  "touches face": "😌",
  "touches cheek": "😌",
  "touches forehead": "😌",
  "touches chin": "😌",
  "touches nose": "👃",
  "touches lips": "👄",
  "touches hair": "💇",
  "touches neck": "👐",
  "touches shoulder": "👐",
  "touches arm": "👐",
  "touches hand": "👐",
  "touches waist": "👐",
  "puts hand on shoulder": "🫂",
  "puts hand on arm": "🫂",
  "puts hand on back": "🫂",
  "pats back": "🫂",
  "pats shoulder": "🫂",
  "pats head": "🫂",
  "pats arm": "🫂",
  "taps shoulder": "👆",
  "taps arm": "👆",
  "taps foot": "👣",
  "rubs arm": "👐",
  "rubs neck": "👐",
  "rubs shoulder": "👐",
  "rubs back": "👐",
  "squeezes shoulder": "🫂",
  "squeezes arm": "🫂",
  "squeezes hand": "🫂",
  "shrugs": "🤷",
  "shrugs shoulders": "🤷",
  "lifts shoulders": "🤷",
  "raises shoulders": "🤷",
  "drops shoulders": "🤷",
  "lowers shoulders": "🤷",
  "relaxes shoulders": "🤷",
  "tenses shoulders": "🤷",
  "rolls shoulders": "🤷",
  "rotates shoulders": "🤷",
  "slouches": "🙍",
  "straightens": "🧍",
  "straightens up": "🧍",
  "stands up straight": "🧍",
  "stands tall": "🧍",
  "leans forward": "🏃",
  "leans back": "🧎",
  "leans in": "🏃",
  "leans away": "🧎",
  "leans closer": "🏃",
  "leans against": "🧎",
  "slumps": "🙍",
  "slumps down": "🙍",
  "slumps forward": "🙍",
  "perks up": "🧍",
  "sits up": "🧍",
  "sits down": "🪑",
  "sits back": "🪑",
  "stands up": "🧍",
  "stands back": "🧍",
  "lies down": "🛌",
  "lies back": "🛌",
  "kneels": "🧎",
  "kneels down": "🧎",
  "crouches": "🧎",
  "crouches down": "🧎",
  "squats": "🧎",
  "squats down": "🧎",
  "bows": "🙇",
  "bows down": "🙇",
  "bows deeply": "🙇",
  "bows slightly": "🙇",
  "bows respectfully": "🙇",
  "curtsies": "💃",
  "salutes": "🫡",
  "stretches": "🧘",
  "stretches out": "🧘",
  "stretches arms": "🧘",
  "stretches legs": "🧘",
  "yawns": "🥱",
  "yawns widely": "🥱",
  "yawns loudly": "🥱",
  "flexes": "💪",
  "flexes muscles": "💪",
  
  // Walking and movement
  "walks": "🚶",
  "walks forward": "🚶",
  "walks backward": "🚶",
  "walks away": "🚶",
  "walks towards": "🚶",
  "walks slowly": "🚶",
  "walks quickly": "🚶",
  "walks cautiously": "🚶",
  "walks confidently": "🚶",
  "walks hesitantly": "🚶",
  "walks nervously": "🚶",
  "walks gracefully": "🚶",
  "walks awkwardly": "🚶",
  "walks proudly": "🚶",
  "walks sheepishly": "🚶",
  "walks angrily": "🚶",
  "walks happily": "🚶",
  "walks sadly": "🚶",
  "walks excitedly": "🚶",
  "walks tiredly": "🚶",
  "walks silently": "🚶",
  "walks noisily": "🚶",
  "walks briskly": "🚶",
  "walks leisurely": "🚶",
  "runs": "🏃",
  "runs forward": "🏃",
  "runs away": "🏃",
  "runs towards": "🏃",
  "runs quickly": "🏃",
  "runs slowly": "🏃",
  "runs frantically": "🏃",
  "runs excitedly": "🏃",
  "runs hurriedly": "🏃",
  "runs frantically": "🏃",
  "jogs": "🏃",
  "sprints": "🏃",
  "dashes": "🏃",
  "rushes": "🏃",
  "hurries": "🏃",
  "skips": "🤸",
  "hops": "🤸",
  "jumps": "⬆️",
  "jumps up": "⬆️",
  "jumps down": "⬇️",
  "jumps forward": "➡️",
  "jumps back": "⬅️",
  "leaps": "⬆️",
  "dives": "🏊",
  "slides": "📉",
  "slips": "📉",
  "trips": "📉",
  "falls": "📉",
  "stumbles": "📉",
  "staggers": "📉",
  "shuffles": "🚶",
  "trudges": "🚶",
  "tiptoes": "🚶",
  "creeps": "🚶",
  "sneaks": "🚶",
  "slinks": "🚶",
  "moves silently": "🚶",
  "moves quietly": "🚶",
  "moves slowly": "🚶",
  "moves quickly": "🚶",
  "moves forward": "🚶",
  "moves backward": "🚶",
  "moves away": "🚶",
  "moves towards": "🚶",
  "steps forward": "🚶",
  "steps backward": "🚶",
  "steps away": "🚶",
  "steps towards": "🚶",
  "paces": "🚶",
  "paces back and forth": "🚶",
  "paces nervously": "🚶",
  "paces anxiously": "🚶",
  "paces impatiently": "🚶",
  "pivots": "🔄",
  "turns": "🔄",
  "turns around": "🔄",
  "spins around": "🔄",
  "whirls around": "🔄",
  "twirls around": "🔄",
  "zigzags": "↔️",
  "circles": "🔄",
  "circles around": "🔄",
  "ascends": "⬆️",
  "descends": "⬇️",
  "climbs": "⬆️",
  "climbs up": "⬆️",
  "climbs down": "⬇️",
  "crawls": "🐛",
  "crawls forward": "🐛",
  "crawls backward": "🐛",
  "crawls away": "🐛",
  "crawls towards": "🐛",
  "scrambles": "🧗",
  "scrambles up": "🧗",
  "scrambles down": "🧗",
  "floats": "🎈",
  "hovers": "🎈",
  "glides": "🏂",
  "glides forward": "🏂",
  "glides backward": "🏂",
  "glides away": "🏂",
  "glides towards": "🏂",
  "swoops": "🦅",
  "swoops down": "🦅",
  "swoops up": "🦅",
  "plunges": "📉",
  "plummets": "📉",
  "soars": "🚀",
  "soars up": "🚀",
  "soars down": "🚀",
  "launches": "🚀",
  "launches forward": "🚀",
  "launches up": "🚀",
  "catapults": "🚀",
  "catapults forward": "🚀",
  "catapults up": "🚀",
  "propels": "🚀",
  "propels forward": "🚀",
  "propels up": "🚀",
  
  // Interactions with objects
  "picks up": "👆",
  "puts down": "👇",
  "lifts": "👆",
  "lowers": "👇",
  "holds": "🤲",
  "holds up": "🤲",
  "carries": "🤲",
  "drops": "👇",
  "tosses": "🤾",
  "throws": "🤾",
  "catches": "🙌",
  "grips": "👊",
  "grasps": "👊",
  "clutches": "👊",
  "squeezes": "👊",
  "clenches": "👊",
  "releases": "👐",
  "gives": "🎁",
  "takes": "🫳",
  "accepts": "🫳",
  "receives": "🫳",
  "offers": "🎁",
  "hands over": "🎁",
  "passes": "🏈",
  "pushes": "👐",
  "pulls": "👐",
  "drags": "👐",
  "shoves": "👐",
  "yanks": "👐",
  "tugs": "👐",
  "twists": "🔄",
  "turns": "🔄",
  "rotates": "🔄",
  "spins": "🔄",
  "flips": "🔄",
  "slides": "📉",
  "taps": "👆",
  "pats": "🫂",
  "pokes": "👆",
  "prods": "👆",
  "jabs": "👆",
  "nudges": "👆",
  "bumps": "👆",
  "touches": "👆",
  "strokes": "👆",
  "caresses": "👆",
  "rubs": "👐",
  "scratches": "👐",
  "pinches": "👐",
  "squeezes": "👐",
  "grabs": "👊",
  "seizes": "👊",
  "snatches": "👊",
  "opens": "📂",
  "closes": "📁",
  "shuts": "📁",
  "slams": "📁",
  "locks": "🔒",
  "unlocks": "🔓",
  "unfastens": "🔓",
  "fastens": "🔒",
  "ties": "🧵",
  "unties": "🧵",
  "buttons": "🔘",
  "unbuttons": "🔘",
  "zips": "🧵",
  "unzips": "🧵",
  
  // Social interactions
  "hugs": "🤗",
  "embraces": "🤗",
  "cuddles": "🤗",
  "snuggles": "🤗",
  "holds tightly": "🤗",
  "squeezes tightly": "🤗",
  "clings to": "🤗",
  "kisses": "😘",
  "kisses cheek": "😘",
  "kisses forehead": "😘",
  "kisses hand": "😘",
  "kisses lips": "😘",
  "pecks cheek": "😘",
  "pecks lips": "😘",
  "pats back": "🫂",
  "pats shoulder": "🫂",
  "pats head": "🫂",
  "pats arm": "🫂",
  "shakes hand": "🤝",
  "high fives": "🙌",
  "fist bumps": "👊",
  "bumps fists": "👊",
  "bumps shoulders": "🫂",
  "nudges": "👆",
  "nudges playfully": "👆",
  "nudges gently": "👆",
  "elbows": "👆",
  "elbows playfully": "👆",
  "elbows gently": "👆",
  "nods to": "🙂",
  "nods at": "🙂",
  "waves to": "👋",
  "waves at": "👋",
  "smiles at": "😊",
  "grins at": "😁",
  "winks at": "😉",
  "glances at": "👀",
  "stares at": "👀",
  "gazes at": "👀",
  "bows to": "🙇",
  "curtsies to": "💃",
  "salutes": "🫡",
  
  // Emotional actions
  "laughs": "😂",
  "laughs loudly": "😂",
  "laughs heartily": "😂",
  "laughs nervously": "😅",
  "laughs awkwardly": "😅",
  "chuckles": "😄",
  "chuckles softly": "😄",
  "chuckles nervously": "😅",
  "giggles": "🤭",
  "giggles softly": "🤭",
  "snickers": "😏",
  "snorts": "😤",
  "guffaws": "🤣",
  "cackles": "😈",
  "howls with laughter": "😂",
  "roars with laughter": "😂",
  "cries": "😢",
  "cries softly": "😢",
  "cries quietly": "😢",
  "cries loudly": "😭",
  "cries uncontrollably": "😭",
  "sobs": "😭",
  "sobs quietly": "😭",
  "sobs loudly": "😭",
  "sobs uncontrollably": "😭",
  "weeps": "😭",
  "weeps quietly": "😭",
  "weeps loudly": "😭",
  "weeps uncontrollably": "😭",
  "wails": "😭",
  "whimpers": "😢",
  "sniffles": "😢",
  "hiccups": "😢",
  "gulps": "😓",
  "clears throat": "😓",
  "sighs": "😮‍💨",
  "sighs deeply": "😮‍💨",
  "sighs heavily": "😮‍💨",
  "sighs softly": "😮‍💨",
  "sighs contentedly": "😌",
  "sighs wearily": "😮‍💨",
  "sighs exasperatedly": "😮‍💨",
  "groans": "😩",
  "groans loudly": "😩",
  "groans softly": "😩",
  "moans": "😩",
  "gasps": "😲",
  "gasps loudly": "😲",
  "gasps softly": "😲",
  "screams": "😱",
  "screams loudly": "😱",
  "screams softly": "😱",
  "shrieks": "😱",
  "yelps": "😱",
  "squeals": "😱",
  "squeaks": "😱",
  "coughs": "😷",
  "coughs loudly": "😷",
  "coughs softly": "😷",
  "sneezes": "🤧",
  "shouts": "📢",
  "shouts loudly": "📢",
  "shouts angrily": "📢",
  "shouts excitedly": "📢",
  "yells": "📢",
  "yells loudly": "📢",
  "yells angrily": "📢",
  "yells excitedly": "📢",
  "cheers": "🎉",
  "cheers loudly": "🎉",
  "cheers excitedly": "🎉",
  "whoops": "🎉",
  "hollers": "📢",
  "whistles": "😙",
  "hums": "🎵",
  "sings": "🎵",
  "sings softly": "🎵",
  "sings loudly": "🎵",
  "chants": "🎵",
  "murmurs": "🔈",
  "mumbles": "🔈",
  "mutters": "🔈",
  "whispers": "🔈",
  "speaks softly": "🔈",
  "speaks loudly": "📢",
  "shushes": "🤫",
  "silences": "🤫",
  "quiets": "🤫",
  "hushes": "🤫",
  
  // Verbal actions
  "says": "💬",
  "says softly": "💬",
  "says quietly": "💬",
  "says loudly": "💬",
  "says angrily": "💬",
  "says happily": "💬",
  "says sadly": "💬",
  "says excitedly": "💬",
  "says nervously": "💬",
  "says anxiously": "💬",
  "says fearfully": "💬",
  "says softly": "💬",
  "says gently": "💬",
  "says roughly": "💬",
  "says harshly": "💬",
  "says kindly": "💬",
  "says meanly": "💬",
  "says firmly": "💬",
  "says sternly": "💬",
  "says seriously": "💬",
  "says jokingly": "💬",
  "says teasingly": "💬",
  "says playfully": "💬",
  "says sarcastically": "💬",
  "says mockingly": "💬",
  "says tauntingly": "💬",
  "says apologetically": "💬",
  "says gratefully": "💬",
  "says thankfully": "💬",
  "says sincerely": "💬",
  "says honestly": "💬",
  "says truthfully": "💬",
  "says lovingly": "💬",
  "says adoringly": "💬",
  "says affectionately": "💬",
  "says sweetly": "💬",
  "says bitterly": "💬",
  "says coldly": "💬",
  "says warmly": "💬",
  "says brightly": "💬",
  "says darkly": "💬",
  "says lightly": "💬",
  "says heavily": "💬",
  "says urgently": "💬",
  "says desperately": "💬",
  "says pleadingly": "💬",
  "says beseechingly": "💬",
  "says imploringly": "💬",
  "says commandingly": "💬",
  "says authoritatively": "💬",
  "says demandingly": "💬",
  "asks": "❓",
  "asks softly": "❓",
  "asks quietly": "❓",
  "asks loudly": "❓",
  "asks angrily": "❓",
  "asks happily": "❓",
  "asks sadly": "❓",
  "asks excitedly": "❓",
  "asks nervously": "❓",
  "asks anxiously": "❓",
  "asks fearfully": "❓",
  "asks softly": "❓",
  "asks gently": "❓",
  "asks roughly": "❓",
  "asks harshly": "❓",
  "asks kindly": "❓",
  "asks meanly": "❓",
  "asks firmly": "❓",
  "asks sternly": "❓",
  "asks seriously": "❓",
  "asks jokingly": "❓",
  "asks teasingly": "❓",
  "asks playfully": "❓",
  "asks sarcastically": "❓",
  "asks mockingly": "❓",
  "asks tauntingly": "❓",
  "asks apologetically": "❓",
  "asks gratefully": "❓",
  "asks thankfully": "❓",
  "asks sincerely": "❓",
  "asks honestly": "❓",
  "asks truthfully": "❓",
  "asks lovingly": "❓",
  "asks adoringly": "❓",
  "asks affectionately": "❓",
  "asks sweetly": "❓",
  "asks bitterly": "❓",
  "asks coldly": "❓",
  "asks warmly": "❓",
  "asks brightly": "❓",
  "asks darkly": "❓",
  "asks lightly": "❓",
  "asks heavily": "❓",
  "asks urgently": "❓",
  "asks desperately": "❓",
  "asks pleadingly": "❓",
  "asks beseechingly": "❓",
  "asks imploringly": "❓",
  "asks commandingly": "❓",
  "asks authoritatively": "❓",
  "asks demandingly": "❓",
  "answers": "💬",
  "replies": "💬",
  "responds": "💬",
  "states": "💬",
  "declares": "💬",
  "announces": "📢",
  "proclaims": "📢",
  "exclaims": "💬",
  "explains": "💬",
  "elaborates": "💬",
  "clarifies": "💬",
  "specifies": "💬",
  "mentions": "💬",
  "remarks": "💬",
  "comments": "💬",
  "notes": "💬",
  "adds": "💬",
  "continues": "💬",
  "finishes": "💬",
  "concludes": "💬",
  "interrupts": "💬",
  "interjects": "💬",
  "cuts in": "💬",
};

// Character mental and emotional states
export const characterStateEmojiMap: Record<string, string> = {
  // Mental states
  "thinks": "🧠",
  "ponders": "🧠",
  "contemplates": "🧠",
  "considers": "🧠",
  "reflects": "🧠",
  "meditates": "🧘",
  "brainstorms": "🧠",
  "analyzes": "🧠",
  "evaluates": "🧠",
  "assesses": "🧠",
  "examines": "🧠",
  "studies": "🧠",
  "investigates": "🧠",
  "explores": "🧠",
  "searches": "🧠",
  "looks for": "🧠",
  "seeks": "🧠",
  "wonders": "🧠",
  "puzzles": "🧠",
  "perplexes": "🧠",
  "confuses": "🧠",
  "baffles": "🧠",
  "mystifies": "🧠",
  "bewilders": "🧠",
  "stumps": "🧠",
  "questions": "🧠",
  "doubts": "🧠",
  "disbelieves": "🧠",
  "distrusts": "🧠",
  "mistrusts": "🧠",
  "suspects": "🧠",
  "misgives": "🧠",
  "hesitates": "🧠",
  "wavers": "🧠",
  "vacillates": "🧠",
  "falters": "🧠",
  "pauses": "🧠",
  "stops": "🧠",
  "halts": "🧠",
  "freezes": "🧠",
  "decides": "🧠",
  "determines": "🧠",
  "resolves": "🧠",
  "chooses": "🧠",
  "selects": "🧠",
  "picks": "🧠",
  "opts": "🧠",
  "elects": "🧠",
  "settles": "🧠",
  "concludes": "🧠",
  
  // Emotional states
  "feels": "❤️",
  "feels happy": "😊",
  "feels sad": "😢",
  "feels angry": "😠",
  "feels anxious": "😰",
  "feels nervous": "😬",
  "feels worried": "😟",
  "feels scared": "😨",
  "feels afraid": "😨",
  "feels terrified": "😱",
  "feels horrified": "😱",
  "feels disgusted": "🤢",
  "feels repulsed": "🤢",
  "feels nauseated": "🤢",
  "feels sick": "🤢",
  "feels exhausted": "😫",
  "feels tired": "😫",
  "feels fatigued": "😫",
  "feels drained": "😫",
  "feels weary": "😫",
  "feels excited": "😃",
  "feels thrilled": "😃",
  "feels elated": "😃",
  "feels ecstatic": "😃",
  "feels overjoyed": "😃",
  "feels joyful": "😃",
  "feels jubilant": "😃",
  "feels amused": "😄",
  "feels entertained": "😄",
  "feels tickled": "😄",
  "feels surprised": "😲",
  "feels shocked": "😲",
  "feels astonished": "😲",
  "feels amazed": "😲",
  "feels awed": "😲",
  "feels stunned": "😲",
  "feels dumbfounded": "😲",
  "feels relieved": "😌",
  "feels unburdened": "😌",
  "feels comforted": "😌",
  "feels soothed": "😌",
  "feels relaxed": "😌",
  "feels calm": "😌",
  "feels peaceful": "😌",
  "feels serene": "😌",
  "feels tranquil": "😌",
  "feels content": "😌",
  "feels satisfied": "😌",
  "feels pleased": "😌",
  "feels gratified": "😌",
  "feels fulfilled": "😌",
  "feels grateful": "🙏",
  "feels thankful": "🙏",
  "feels appreciative": "🙏",
  "feels indebted": "🙏",
  "feels beholden": "🙏",
  "feels proud": "😊",
  "feels accomplished": "😊",
  "feels achieved": "😊",
  "feels successful": "😊",
  "feels guilty": "😔",
  "feels remorseful": "😔",
  "feels regretful": "😔",
  "feels sorry": "😔",
  "feels apologetic": "😔",
  "feels ashamed": "😔",
  "feels embarrassed": "😳",
  "feels mortified": "😳",
  "feels humiliated": "😳",
  "feels disgraced": "😳",
  "feels lonely": "😔",
  "feels isolated": "😔",
  "feels abandoned": "😔",
  "feels forsaken": "😔",
  "feels rejected": "😔",
  "feels unwanted": "😔",
  "feels unloved": "😔",
  "feels betrayed": "💔",
  "feels deceived": "💔",
  "feels cheated": "💔",
  "feels tricked": "💔",
  "feels fooled": "💔",
  "feels duped": "💔",
  "feels used": "💔",
  "feels manipulated": "💔",
  "feels exploited": "💔",
  "feels jealous": "💚",
  "feels envious": "💚",
  "feels covetous": "💚",
  "feels resentful": "😒",
  "feels bitter": "😒",
  "feels indignant": "😒",
  "feels offended": "😒",
  "feels insulted": "😒",
  "feels hurt": "💔",
  "feels wounded": "💔",
  "feels injured": "💔",
  "feels damaged": "💔",
  "feels broken": "💔",
  "feels shattered": "💔",
  "feels crushed": "💔",
  "feels devastated": "💔",
  "feels hopeful": "🙏",
  "feels optimistic": "🙏",
  "feels positive": "🙏",
  "feels encouraging": "🙏",
  "feels hopeless": "😔",
  "feels despairing": "😔",
  "feels desperate": "😔",
  "feels discouraged": "😔",
  "feels disheartened": "😔",
  "feels depressed": "😔",
  "feels melancholic": "😔",
  "feels gloomy": "😔",
  "feels miserable": "😔",
  "feels wretched": "😔",
  "feels loved": "❤️",
  "feels adored": "❤️",
  "feels cherished": "❤️",
  "feels treasured": "❤️",
  "feels valued": "❤️",
  "feels appreciated": "❤️",
  "feels respected": "❤️",
  "feels honored": "❤️",
  "feels admired": "❤️",
  "feels esteemed": "❤️",
  "feels revered": "❤️",
  "feels in love": "❤️",
  "feels romantic": "❤️",
  "feels affectionate": "❤️",
  "feels tender": "❤️",
  "feels passionate": "❤️",
  "feels lustful": "❤️",
  "feels aroused": "❤️",
  "feels excited": "❤️",
  "feels stimulated": "❤️",
  "feels safe": "🛡️",
  "feels secure": "🛡️",
  "feels protected": "🛡️",
  "feels sheltered": "🛡️",
  "feels guarded": "🛡️",
  "feels vulnerable": "🛡️",
  "feels exposed": "🛡️",
  "feels defenseless": "🛡️",
  "feels helpless": "🛡️",
  "feels powerless": "🛡️",
  "feels weak": "🛡️",
  "feels strong": "💪",
  "feels powerful": "💪",
  "feels mighty": "💪",
  "feels capable": "💪",
  "feels competent": "💪",
  "feels confident": "💪",
  "feels self-assured": "💪",
  "feels self-confident": "💪",
  "feels uncertain": "😕",
  "feels unsure": "😕",
  "feels doubtful": "😕",
  "feels insecure": "😕",
  "feels self-conscious": "😕",
  "feels inadequate": "😕",
  "feels insufficient": "😕",
  "feels inferior": "😕",
  "feels unworthy": "😕",
  "feels defeated": "😞",
  "feels beaten": "😞",
  "feels conquered": "😞",
  "feels victorious": "🏆",
  "feels triumphant": "🏆",
  "feels successful": "🏆",
  "feels accomplished": "🏆",
  "feels satisfied": "🏆",
  "feels pleased": "🏆",
  "feels content": "🏆",
  "feels angry": "😠",
  "feels mad": "😠",
  "feels furious": "😡",
  "feels enraged": "😡",
  "feels outraged": "😡",
  "feels infuriated": "😡",
  "feels irate": "😡",
  "feels irritated": "😠",
  "feels annoyed": "😠",
  "feels aggravated": "😠",
  "feels agitated": "😠",
  "feels calm": "😌",
  "feels sane": "😌",
  "feels composed": "😌",
  "feels gentle": "😌",
  "feels tender": "😌",
  "feels sweet": "😌",
  "feels fierce": "😠",
  "feels wild": "😠",
  "feels feral": "😠",
  "feels turbulent": "😵‍💫",
  "feels tumultuous": "😵‍💫",
  "feels chaotic": "😵‍💫",
  "feels emotional": "😢",
  "feels overwhelmed": "😵‍💫",
  "feels numb": "😶",
  "feels empty": "😶",
  "feels hollow": "😶",
  "feels void": "😶",
  "feels vacant": "😶",
};

// Combine all mappings 
export const characterCompleteEmojiMap: Record<string, string> = {
  ...characterFacialEmojiMap,
  ...characterActionEmojiMap,
  ...characterStateEmojiMap
};