// Emoji mappings for expressions
// Maps text expressions to their emoji equivalents
export const expressionToEmojiMap: Record<string, string> = {
  // Basic expressions
  "*nods*": "👍",
  "*shakes head*": "🙅",
  "*laughs*": "😂",
  "*laughs softly*": "😊",
  "*laughs nervously*": "😅",
  "*giggles*": "😄",
  "*snorts*": "😆",
  "*smirks*": "😏",
  "*grins*": "😁",
  "*grins sheepishly*": "😅",
  "*smiles warmly*": "🙂",
  "*smiles sadly*": "😔",
  "*smiles weakly*": "😕",
  "*frowns*": "☹️",
  "*pouts*": "😞",
  "*gasps*": "😯",
  "*gasps loudly*": "😲",
  "*sighs*": "😔",
  "*sniffs*": "🤧",
  "*sneezes*": "🤧",
  "*coughs*": "😷",
  "*yawns*": "🥱",
  "*cries*": "😢",
  "*sobs*": "😭",
  "*wails*": "😩",
  "*whimpers*": "😟",
  "*gulps*": "😰",
  "*winces*": "😣",
  "*grimaces*": "😬",
  "*groans*": "😩",
  "*moans*": "😫",
  "*screams*": "😱",
  "*shrieks*": "😨",
  "*gasps dramatically*": "😧",
  "*stares*": "👀",
  "*stares blankly*": "😐",
  "*stares in shock*": "😲",
  "*narrows eyes*": "😒",
  "*glares*": "😠",
  "*squints*": "😑",
  "*rolls eyes*": "🙄",
  "*raises eyebrow*": "🤨",
  "*arches brow*": "🤔",
  "*tilts head*": "🤔",
  "*cocks head*": "🧐",
  "*nods slowly*": "👌",
  "*shrugs*": "🤷",
  "*facepalms*": "🤦",
  "*holds head in hands*": "🤯",
  "*rubs temples*": "😣",
  "*covers face*": "😖",
  "*scrunches up face*": "😕",
  "*looks confused*": "😕",
  "*looks surprised*": "😮",
  "*looks scared*": "😨",
  "*looks amused*": "😄",
  "*looks unimpressed*": "😑",
  "*looks skeptical*": "🧐",
  "*looks annoyed*": "😒",
  "*looks angry*": "😠",
  "*looks disappointed*": "😞",
  "*looks hopeful*": "🤞",
  "*looks excited*": "😃",
  "*looks embarrassed*": "😳",
  "*blushes*": "😊",
  "*turns red*": "😳",
  "*giggles nervously*": "😅",
  "*covers mouth*": "🤭",
  "*waves*": "👋",
  "*waves shyly*": "👋",
  "*gives thumbs up*": "👍",
  "*gives thumbs down*": "👎",
  "*claps*": "👏",
  "*cheers*": "🎉",
  "*jumps*": "🕴️",
  "*dances*": "💃",
  "*bows*": "🙇",
  "*salutes*": "🫡",
  "*points*": "👉",
  "*points at self*": "🙋",
  "*raises hand*": "✋",
  "*lowers hand*": "🤚",
  "*holds up hand*": "✋",
  "*crosses arms*": "😒",
  "*folds arms*": "😑",
  "*puts hands on hips*": "😤",
  "*shrugs helplessly*": "🤷",
  "*nods eagerly*": "😃",
  "*nods solemnly*": "😔",
  "*shakes head slowly*": "😞",
  "*taps foot*": "🦶",
  "*stomps*": "😠",
  "*paces*": "🧍‍♂️",
  "*sits down*": "🪑",
  "*stands up*": "🧍",
  "*leans back*": "😌",
  "*leans forward*": "🧐",
  "*tilts head in confusion*": "🤔",
  "*fidgets*": "🫨",
  "*bites lip*": "😬",
  "*chews nails*": "😬",
  "*scratches head*": "🤷",
  "*rubs neck*": "😓",
  "*looks away*": "😳",
  "*avoids eye contact*": "🙈",
  "*stares at floor*": "😞",
  "*snaps fingers*": "🫰",
  "*cracks knuckles*": "👐",
  "*takes deep breath*": "😮‍💨",
  "*exhales slowly*": "😤",
  "*inhales sharply*": "😯",
  "*trembles*": "😰",
  "*shivers*": "🥶",
  "*sweats*": "😓",
  "*starts sweating*": "🫣",
  "*gulps nervously*": "😰",
  "*chuckles*": "😄",
  "*chuckles darkly*": "😏",
  "*mutters*": "🤐",
  "*mumbles*": "😶",
  "*whispers*": "🤫",
  "*yells*": "🗣️",
  "*shouts*": "📣",
  "*groans loudly*": "😩",
  "*screeches*": "😱",
  "*makes a face*": "😖",
  "*pulls a face*": "😝",
  "*sticks out tongue*": "😛",
  "*winks*": "😉",
  "*blows kiss*": "😘",
  "*makes heart shape*": "❤️",
  "*crosses fingers*": "🤞",
  "*gestures wildly*": "🗯️",
  "*throws hands up*": "😤",
  "*throws arms around*": "🤗",
  "*hugs*": "🤗",
  "*high fives*": "🙌",
  "*fist bumps*": "👊",
  "*covers ears*": "🙉",
  "*covers eyes*": "🙈",
  "*covers mouth in shock*": "😮",
  "*looks proud*": "😌",
  "*beams*": "😄",
  "*glows with pride*": "😌",
  "*looks downcast*": "😢",
  "*hangs head*": "😞",
  "*chuckles awkwardly*": "😅",
  "*laughs maniacally*": "😈",
  "*laughs evilly*": "😈",
  "*cackles*": "😆",
  "*sighs deeply*": "😔",
  "*looks thoughtful*": "🤔",
  "*ponders*": "🤔",
  "*scratches chin*": "🤨",
  "*strokes beard*": "🧔",
  "*twirls hair*": "💁",
  "*tugs at sleeve*": "🧥",
  "*adjusts glasses*": "🤓",
  "*blinks*": "😐",
  "*squints in disbelief*": "😑",
  "*looks stunned*": "😲",
  "*shakes with rage*": "😡",
  "*turns away*": "😠",
  "*throws something*": "💢",
  "*slams fist*": "👊",
  "*flips table*": "(╯°□°）╯︵ ┻━┻",
  
  // Additional expressions
  "*grovels*": "🙇",
  "*pleads*": "🥺",
  "*begs*": "🙏",
  "*prays*": "🙏",
  "*meditates*": "🧘",
  "*zones out*": "💤",
  "*daydreams*": "💭",
  "*spaces out*": "😶‍🌫️",
  "*snaps out of it*": "😳",
  "*blanks out*": "😐",
  "*looks bored*": "😒",
  "*taps fingers*": "🫰",
  "*drums fingers*": "🥁",
  "*bounces foot*": "🦶",
  "*clicks tongue*": "😬",
  "*scoffs*": "😏",
  "*chuckles dryly*": "😒",
  "*rolls shoulders*": "🧍",
  "*cracks neck*": "💢",
  "*tilts head back*": "😤",
  "*throws back head laughing*": "😂",
  "*leans on wall*": "🧍‍♂️",
  "*leans over*": "👀",
  "*leans in close*": "🫣",
  "*backs away*": "😳",
  "*jumps back*": "😨",
  "*flinches*": "😖",
  "*ducks*": "🙇‍♂️",
  "*peeks*": "🙈",
  "*glances away*": "😶",
  "*glances nervously*": "😬",
  "*glances sideways*": "👀",
  "*stifles laugh*": "😆",
  "*snickers*": "😏",
  "*chortles*": "😄",
  "*giggles uncontrollably*": "🤭",
  "*wheezes*": "😤",
  "*hyperventilates*": "😰",
  "*chokes*": "😵",
  "*coughs nervously*": "😬",
  "*holds breath*": "😶",
  "*puffs cheeks*": "😗",
  "*blows out air*": "😤",
  "*grits teeth*": "😣",
  "*bares teeth*": "😬",
  "*snarls*": "😠",
  "*growls*": "😡",
  "*hisses*": "😾",
  "*bares fangs*": "😈",
  "*licks lips*": "😋",
  "*puckers lips*": "😚",
  "*makes kissy face*": "😘",
  "*squishes cheeks*": "🥺",
  "*sticks out bottom lip*": "😢",
  "*crosses fingers behind back*": "🤞",
  "*shakes fist*": "👊",
  "*punches air*": "🥊",
  "*air kicks*": "🦵",
  "*does finger guns*": "🤠",
  "*salutes sarcastically*": "😏",
  "*thumbs up sarcastically*": "😒",
  "*makes peace sign*": "✌️",
  "*flips hair*": "💁‍♀️",
  "*snaps fingers sassily*": "🧚‍♀️",
  "*does twirl*": "💃",
  "*poses dramatically*": "🎭",
  "*collapses dramatically*": "😩",
  "*lays down*": "🛌",
  "*faceplants*": "🤕",
  "*bangs head on desk*": "😫",
  "*bangs head against wall*": "😩",
  "*slams door*": "🚪",
  "*slams laptop shut*": "💻",
  "*throws phone*": "📱💥",
  "*screams into pillow*": "😫🛏️",
  "*melts into floor*": "🫠",
  "*vanishes*": "🫥",
  "*evaporates*": "💨",
  "*floats away*": "🎈",
  "*ascends*": "☁️",
  "*descends into madness*": "😵‍💫",
  "*stares into void*": "🌀",
  "*panics*": "😱",
  "*runs away*": "🏃",
  "*runs in circles*": "🔁",
  "*spins*": "🌀",
  "*teleports out*": "🌀💨",
  "*appears suddenly*": "✨",
  "*materializes*": "💫",
  "*disappears in a puff*": "💨",
  "*fades away*": "🌫️",
  "*turns to dust*": "🪦",
  "*explodes*": "💥",
  "*implodes*": "🫥",
  "*crashes*": "💥",
  "*freezes*": "🧊",
  "*gets stuck*": "🧱",
  "*breaks down*": "😭",
  "*short circuits*": "🤖💢",
  "*dies inside*": "😩",
  "*reboots*": "🔁",
  "*glitches*": "🖥️",
  "*404s*": "❌",
  "*malfunctions*": "⚠️",
  
  // Even more expressions
  "*presses lips together*": "😶",
  "*grins mischievously*": "😏",
  "*twirls mustache*": "🧐",
  "*looks innocent*": "😇",
  "*pretends not to know*": "🤥",
  "*acts surprised*": "😲",
  "*acts offended*": "😤",
  "*acts clueless*": "😶",
  "*acts cool*": "😎",
  "*acts dramatic*": "🎭",
  "*acts suspicious*": "🕵️",
  "*side-eyes*": "👀",
  "*deadpans*": "😐",
  "*monologues*": "🎙️",
  "*narrates*": "📖",
  "*commentates*": "🎤",
  "*breaks fourth wall*": "🪞",
  "*narrates dramatically*": "🎬",
  "*voice cracks*": "🫨",
  "*clears throat*": "😬",
  "*stares at phone*": "📱👀",
  "*checks clock again*": "⏰😩",
  "*scrolls endlessly*": "📱🌀",
  "*accidentally likes post*": "😳❤️",
  "*wakes up late*": "⏰🛌",
  "*forgets homework*": "😱📚",
  "*runs out the door*": "🏃🚪",
  "*misses ride*": "🚗💨",
  "*brain goes brr*": "🧠💨",
  "*social battery dead*": "🔋❌",
  "*forgets how to human*": "🤖❓",
  "*wants to scream into void*": "😱🌌",
  "*doesn't even have energy to cry*": "😐💧",
  "*scrolls dead-eyed*": "👁️📱",
  "*forgets what happiness feels like*": "😶‍🌫️🫠",

  // Common text expressions
  "*sigh*": "😔",
  "*smile*": "🙂",
  "*laugh*": "😂",
  "*crying*": "😢",
  "*blush*": "😊",
  "*happy*": "😄",
  "*sad*": "😔",
  "*angry*": "😠",
  "*confused*": "😕",
  "*shocked*": "😲",
  "*thumbs up*": "👍",
  "*thumbs down*": "👎",
  "*ok*": "👌",
  "*yes*": "✅",
  "*no*": "❌",
  "*hug*": "🤗",
  "*wave*": "👋",
  "*shrug*": "🤷",
  "*eye roll*": "🙄",
  "*wink*": "😉",
  "*facepalm*": "🤦",
};

// Function to replace text expressions with emojis
export function replaceExpressionsWithEmojis(text: string): string {
  let result = text;
  
  // First, handle the case where expressions are wrapped with asterisks
  for (const [expression, emoji] of Object.entries(expressionToEmojiMap)) {
    // Replace the exact expression (with asterisks)
    const regex = new RegExp(expression.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g');
    result = result.replace(regex, emoji);
  }
  
  return result;
}

// Function to preprocess user message to preserve emojis
export function preserveEmojis(text: string): string {
  return text; // Already preserved as-is since they're Unicode characters
}