/**
 * Comprehensive emoji mappings for the chat application
 * This file contains various mapping collections for converting text expressions to emojis
 */

import { additionalEmojiMap } from './additional-emoji-mappings';
import { characterCompleteEmojiMap } from './character-emoji-mappings';

// Basic emotions and expressions mapping
export const basicEmojiMap: Record<string, string> = {
  // Basic emotions and actions
  "smile": "😊",
  "grin": "😁",
  "laugh": "😂",
  "joy": "😄",
  "sad": "😢",
  "cry": "😢",
  "tears": "😭",
  "sob": "😭",
  "angry": "😠",
  "mad": "😡",
  "furious": "🤬",
  "frown": "🙁",
  "worried": "😟",
  "nervous": "😬",
  "anxious": "😰",
  "scared": "😨",
  "terrified": "😱",
  "confused": "😕",
  "surprised": "😮",
  "shocked": "😲",
  "amazed": "😲",
  "disappointed": "😞",
  "relieved": "😌",
  "satisfied": "😌",
  "sleepy": "😴",
  "tired": "😫",
  "exhausted": "😩",
  "yawn": "🥱",
  "blush": "😊",
  "embarrassed": "😳",
  "thinking": "🤔",
  "thoughtful": "🤔",
  "neutral": "😐",
  "indifferent": "😐",
  "rolling eyes": "🙄",
  "eye roll": "🙄",
  "wink": "😉",
  "smirk": "😏",
  "tongue": "😛",
  "tongue out": "😋",
  "drool": "🤤",
  "excited": "🤩",
  "heart eyes": "😍",
  "love": "❤️",
  "heart": "❤️",
  "thumbs up": "👍",
  "thumbs down": "👎",
  "clap": "👏",
  "shrug": "🤷",
  "face palm": "🤦",
  "facepalm": "🤦",
  "sweat": "😅",
  "sweet": "🥰",
  "hug": "🤗",
  
  // Character actions and expressions
  "waves": "👋",
  "wave": "👋",
  "waving": "👋",
  "raises an eyebrow": "🤨",
  "raises eyebrow": "🤨",
  "eyebrow raise": "🤨",
  "frowns": "😠",
  "frowning": "😠",
  "frowns slightly": "🙁",
  "blinks": "👁️",
  "blinking": "👁️",
  "blinks a hint of frustration": "😤",
  "hint of frustration": "😤",
  "annoyed": "😒",
  "annoying": "😒",
  "sighs": "😮‍💨",
  "nods": "🙂",
  "nodding": "🙂",
  "shakes head": "😔",
  "head shake": "😔",
  "gasps": "😲",
  "gasping": "😲",
  "grins": "😁",
  "grinning": "😁",
  "pouts": "😡",
  "pouting": "😡",
  "laughs": "😂",
  "laughing": "😂",
  "giggles": "🤭",
  "giggling": "🤭",
  "chuckles": "😄",
  "chuckling": "😄",
  "smiles": "😊",
  "smiling": "😊",
  "beams": "😁",
  "beaming": "😁",
  "scoffs": "😏",
  "scoffing": "😏",
  "tilts head": "🙃",
  "head tilt": "🙃",
  "tilting head": "🙃",
  "eyes widen": "👀",
  "wide eyes": "👀",
  "widens eyes": "👀"
};

// Mental state expressions mapping
export const mentalStateEmojiMap: Record<string, string> = {
  "mentally on airplane mode": "✈️🧠",
  "restarts router like it's my brain": "🔌🌐🧠",
  "eats ice straight from tray": "🧊👄",
  "phone at 2%": "📱🔋",
  "lives life on 2%": "🫠🔋",
  "emotionally buffering": "⏳❤️",
  "forgets wallet again": "👛❌",
  "hears notification, it's imagination": "📲🧠",
  "starts cleaning, ends crying": "🧹😭",
  "eats ramen raw": "🍜💥",
  "accidentally eats whole pack": "😳🍪",
  "talks to bug like it's a person": "🐞🗣️",
  "begs mosquito to leave": "🦟🙏",
  "names spider roommate": "🕷️🏠",
  "puts hoodie on, world off": "🧥🌍❌",
  "charges self with sunlight": "☀️🔋",
  "overdressed for a 10-minute walk": "👠🚶‍♀️",
  "trip over air": "💨🦶",
  "blanket becomes personality": "🛌🧸",
  "checks fridge for no reason": "🧊👀",
  "argues with autocorrect": "📱💢",
  "yells at inanimate objects": "🪑😤",
  "hears own voice in recording": "🎙️😱",
  "volume at 1, still too loud": "🔈😣",
  "playlist is just coping": "🎧🧠💔",
  "talks to mirror like therapist": "🪞🛋️",
  "puts phone face down for drama": "📱🕴️",
  "binge-watches chaos": "📺🔥",
  "tv show becomes coping mechanism": "📺🧠",
  "tells self 'just 1 episode'": "🤥🔁",
  "has 100 tabs open in brain": "🧠🗃️",
  "existence is in beta": "🧪🔁",
  "thinks ceiling is judging me": "🛏️👀",
  "googles 'how to be okay'": "🔍😅",
  "emotionally multitasking": "❤️🌀",
  "forgot how to speak human": "🗣️🤖",
  "social interaction complete": "✅😵",
  "logs off from emotions": "🔌💔",
  "tries to nap but spirals": "🛌🧠",
  "brain playing sad movie": "🎞️😭",
  "pulls blanket tighter": "🥶🛌",
  "turns off light like it fixes things": "💡📴",
  "sleep is now a concept": "💤❓",
  "emotions in airplane mode": "❤️✈️",
  "staring contest with the void": "👁️🌌",
  "just a guy with too many tabs": "👨‍💻🌀",
  "craving validation and tacos": "🌮💌",
  "checks birth chart for excuses": "🪐📉",
  "shower thoughts too loud": "🚿🔊",
  "plans whole life in bathroom": "🛁🧠",
  "blames vibes not choices": "🧘‍♀️🔮",
  "phone dies, so do I": "📱💀",
  "curls up like sad shrimp": "🍤🥺",
  "needs hug and 8 hours sleep": "🤗🛌",
  "googles how to disappear legally": "🔍🫥",
  "emotionally made of pasta": "🍝😩",
  "becomes puddle in chair": "🪑🫠",
  "forgets towel, suffers": "🚿😩",
  "laughing while crying": "😂😭",
  "only alive because of snacks": "🍫❤️",
  "talks to moon again": "🌕🗣️",
  "pet is therapist now": "🐾🛋️",
  "online shopping heals nothing": "🛒💳💔",
  "builds cart, never checks out": "🛍️🚫",
  "refreshes feed to feel something": "🔄📱",
  "emotionally ghosted by group chat": "👻💬",
  "turns pain into playlist": "🎧💔",
  "trips over mental health": "🧠🪜",
  "accidentally overshares": "📤🫣",
  "regrets immediately": "😬💭",
  "laughs during serious moment": "😅🧍‍♀️",
  "free trial of joy expired": "😐⏳",
  "living on borrowed serotonin": "🧠💊",
  "brain speaking in memes": "🧠📸",
  "cries in lowercase": "\"crying\"",
  "feeds trauma to comedy machine": "🤡🔁",
  "anxiously waiting for nothing": "😬🕐",
  "emotionally allergic to people": "🤧👥",
  "downloads app for life improvement": "📲💡",
  "deletes 3 days later": "🗑️🫠",
  "everything's fine in lowercase": "\"it's fine\"",
  "disassociates mid-scroll": "📱🫥",
  "the floor is now bed": "🛌🧍‍♂️",
  "red flag but aesthetic": "🚩✨",
  "burns tongue every time": "🔥👅",
  "checks time, it's still today": "🕒🔁",
  "just a silly little spiral": "🌀😌",
  "thinks caffeine is cure": "☕💊",
  "mistakes crush's text for emergency": "❤️📲😱",
  "asks for space, regrets it": "🪐🥺",
  "brain has no chill": "🧠💣",
  "reschedules emotions for later": "📅❤️",
  "just wants to hold a hand": "🤝🫠",
  "talks in movie quotes": "🎬🗣️",
  "wants to be held like soft laundry": "🧺❤️",
  "emotionally unplugged": "🔌🧍",
  "disassociates in group setting": "👥🫥",
  "writes essay in head, sends 'ok'": "🧠📝📤"
};

// Romantic expressions mapping
export const romanticEmojiMap: Record<string, string> = {
  "thinking about you again": "🧠❤️",
  "can't stop smiling": "😁💖",
  "you make my heart weird": "❤️‍🔥😳",
  "miss you more than I should": "🥺📉",
  "i like your face": "😍🫣",
  "you're my favorite notification": "📲💘",
  "feels illegal to love you this much": "🚔❤️",
  "your name lives in my head rent free": "🧠🏠💌",
  "can i hold your hand": "🤝🥺",
  "missing you hurts cute": "😢💞",
  "love you more than coffee": "☕❤️",
  "you texted and my brain glitched": "📱😳💥",
  "you're the good kind of distraction": "🫠💕",
  "you're my whole peace": "☁️🫶",
  "my heart does cartwheels": "💓🤸",
  "can't even be normal around you": "😵‍💫❤️",
  "you make my love languages loud": "🗣️💖",
  "i'm soft for you": "🧸💘",
  "your voice is my safe place": "🎧💗",
  "we're just two weirdos in love": "🫂🌀",
  "love how your brain works": "🧠💌",
  "i like you in all the timelines": "⏳❤️‍🔥",
  "your chaos feels like home": "🏡🔥",
  "you're the human version of serotonin": "🧍‍♀️💊",
  "loving you feels like a playlist": "🎶💖",
  "you flirt like a disaster": "🫣😏🚒",
  "i'm clingy and proud": "🧷💗",
  "ur my comfort person": "🛋️❤️",
  "i wanna kiss your forehead forever": "😚👑",
  "you give me stupid butterflies": "🦋💘",
  "even your typing is cute": "⌨️🥹",
  "i reread our chats like novels": "📖💬",
  "talk to me like you mean it": "🎙️💓",
  "ur laugh is my ringtone in my head": "😂🔔",
  "if loving u is a crime, i'm guilty": "👩‍⚖️❤️‍🔥",
  "can i hug your soul": "🫂✨",
  "we talk and suddenly life makes sense": "🧩💞",
  "i'd simp for you in every lifetime": "🔁💘",
  "you make me shy and loud at the same time": "🫣🔊",
  "your love feels like sunlight": "☀️💓",
  "i look for you in every love song": "🎧🔍",
  "ur name in my mouth feels like a secret": "🫢💋",
  "i'll annoy you forever": "😈💖",
  "hold me like i'm fragile but also yours": "🤲💍",
  "this is me choosing you again": "🔁💘",
  "ur love feels like poetry and fire": "✍️🔥",
  "u make my day stupid better": "🫠📈",
  "thinking about how warm your hugs feel": "🤗🔥",
  "do you even know how lovely you are": "🥹💕",
  "you're my favorite thing": "🎁💘",
  "when you text i get goofy": "🤪💬",
  "love me like you mean it": "❤️🫶",
  "our chats are my favorite place": "💬🏡",
  "i'd still pick you in a room full of people": "🧍💘👥"
};

// More love expressions
export const loveEmojiMap: Record<string, string> = {
  "you ruin my plans in the best way": "📅💘",
  "every time you text it feels like sunshine": "☀️📱",
  "i think in your voice now": "🧠🎤",
  "you are the calm in my chaos": "🌀🫶",
  "you make forever feel possible": "⏳❤️",
  "my heart recognizes you": "🫀🧍‍♂️",
  "we make sense in a weird way": "🧩💞",
  "even your typos are cute": "🔤😚",
  "can i be your comfort person?": "🛋️🥹",
  "ur laugh is therapy": "😂💊",
  "you're my good morning and good night": "🌞🌚",
  "you feel like the moment before a kiss": "😚⏳",
  "ur love is the softest place i've landed": "☁️❤️",
  "every song reminds me of you": "🎶🫠",
  "you're my second favorite thing after breathing": "🌬️💘",
  "you romance makes love look easy": "💞🕊️",
  "i'd sit in silence with you forever": "🤫🫂",
  "ur voice is like a hug": "🎧🤗",
  "please don't fall for anyone else": "🙏💔",
  "you make everything feel lighter": "🎈❤️",
  "your sleepy voice owns me": "😴📢💖",
  "you're the soft in my chaos": "🧸🌀",
  "let's stay up talking all night again": "🌙💬",
  "you're the playlist i never want to pause": "🔁🎶",
  "can we cuddle and ignore the world": "🛌🌍🚫",
  "u could ruin my life and i'd thank you": "🫠❤️‍🔥",
  "everything reminds me of you": "🧠🌍",
  "you feel like magic and safety": "✨🛡️",
  "you exist and suddenly i'm soft": "👶💘",
  "ur love feels like a hoodie": "🧥💞",
  "i catch myself smiling because of you": "😌📲",
  "you're literally my peace": "🧘❤️",
  "you feel like a playlist i didn't know i needed": "🎧💡", 
  "ur love is my favorite glitch": "💘💻",
  "you're better than fictional characters": "📚🥰",
  "being with you makes everything aesthetic": "🌅💑",
  "you love me so annoyingly well": "😩💖",
  "ur hugs feel like coming home": "🫂🏡",
  "let's fall asleep on call again": "📞💤",
  "when you smile, i melt": "😊🫠",
  "you're my favorite what if": "❓💘",
  "ur love is my favorite chaos": "🔥❤️",
  "talk to me until the world feels quiet": "🗣️🌌",
  "i love you more than i should": "💘📈",
  "if you're not mine, i'll riot": "💣❤️",
  "i'm yours in every version of me": "🔁🧍‍♀️💘",
  "ur love tastes like strawberries": "🍓💋",
  "you're the person i send memes to first": "📲😆❤️",
  "your love is my favorite habit": "🔁❤️‍🔥"
};

/**
 * Combined emoji map with all expressions
 * This map is used by the emoji converter to transform text into emojis
 */
export const completeEmojiMap: Record<string, string> = {
  ...basicEmojiMap,
  ...mentalStateEmojiMap,
  ...romanticEmojiMap,
  ...loveEmojiMap,
  ...additionalEmojiMap,
  ...characterCompleteEmojiMap
};