import { type Character } from "@shared/characters";

// Comprehensive emoji mapping for actions and expressions found inside asterisks
// This helps convert text descriptions to actual emojis
const emojiMap: Record<string, string> = {
  // Basic emotions and actions
  "smile": "😊",
  "grin": "😁",
  "laugh": "😂",
  "joy": "😄",
  "sigh": "😔",
  "sad": "😢",
  "cry": "😢",
  "tears": "😭",
  "sob": "😭",
  "angry": "😠",
  "mad": "😡",
  "furious": "🤬",
  "frown": "🙁",
  "worried": "😟",
  "nervous": "😬",
  "anxious": "😰",
  "scared": "😨",
  "terrified": "😱",
  "confused": "😕",
  "surprised": "😮",
  "shocked": "😲",
  "amazed": "😲",
  "disappointed": "😞",
  "relieved": "😌",
  "satisfied": "😌",
  "sleepy": "😴",
  "tired": "😫",
  "exhausted": "😩",
  "yawn": "🥱",
  "blush": "😊",
  "embarrassed": "😳",
  "thinking": "🤔",
  "thoughtful": "🤔",
  "neutral": "😐",
  "indifferent": "😐",
  "rolling eyes": "🙄",
  "eye roll": "🙄",
  "wink": "😉",
  "smirk": "😏",
  "tongue": "😛",
  "tongue out": "😋",
  "drool": "🤤",
  "excited": "🤩",
  "heart eyes": "😍",
  "love": "❤️",
  "heart": "❤️",
  "thumbs up": "👍",
  "thumbs down": "👎",
  "clap": "👏",
  "shrug": "🤷",
  "face palm": "🤦",
  "facepalm": "🤦",
  "sweat": "😅",
  "sweet": "🥰",
  "hug": "🤗",
  
  // Head movements
  "nods slowly": "👍",
  "nods enthusiastically": "😀👍",
  "shakes head": "🙅‍♂️",
  "shrugs helplessly": "🤷",
  "throws hands up": "🙌",
  "slaps forehead": "🤦",
  "facepalms hard": "🤦‍♂️",
  "sighs deeply": "😮‍💨",
  "gasps audibly": "😲",
  "inhales sharply": "😧",
  "holds chest": "🫀",
  "clutches pearls": "😱",
  "stares blankly": "😐",
  "raises eyebrow": "🤨",
  "furrows brows": "😠",
  "squints slightly": "🧐",
  "narrows eyes": "😒",
  "widens eyes": "😳",
  "eyes dart around": "👀",
  "shifts uncomfortably": "😬",
  "looks around nervously": "😟",
  "bites lip": "😬",
  "taps foot": "👟",
  "bounces knee": "🦵",
  "folds arms": "😤",
  "crosses arms": "🙅‍♀️",
  "tilts head": "🤔",
  "tilts head confusedly": "😕",
  "smirks": "😏",
  "pouts": "😢",
  
  // Advanced actions
  "presses lips together": "😶",
  "grins mischievously": "😏",
  "twirls mustache": "🧐",
  "looks innocent": "😇",
  "pretends not to know": "🤥",
  "acts surprised": "😲",
  "acts offended": "😤",
  "acts clueless": "😶",
  "acts cool": "😎",
  "acts dramatic": "🎭",
  "acts suspicious": "🕵️",
  "side-eyes": "👀",
  "deadpans": "😐",
  "monologues": "🎙️",
  "narrates": "📖",
  "commentates": "🎤",
  "breaks fourth wall": "🪞",
  "narrates dramatically": "🎬",
  "voice cracks": "🫨",
  "clears throat": "😬",
  "adjusts tie": "👔",
  "adjusts hat": "🎩",
  "fixes hair": "💇",
  "reapplies makeup": "💄",
  "checks reflection": "🪞",
  "pops collar": "😎",
  "struts": "🕺",
  "poses for camera": "📸",
  "strikes pose": "💃",
  "does peace sign": "✌️",
  "throws gang sign": "🫰",
  "salutes stiffly": "🫡",
  "waves dramatically": "👋",
  "nods curtly": "🙃",
  "glances quickly": "👀",
  "squints suspiciously": "🧐",
  "glowers": "😠",
  "glances knowingly": "😏",
  "winks slyly": "😉",
  "twirls finger": "🔄",
  "cracks fingers": "✋",
  "pats back": "🤗",
  "rubs back": "💆",
  "hugs tightly": "🤗",
  "grabs hand": "✋",
  "holds hands": "🤝",
  "shakes hands": "🤝",
  
  // Phone and tech related
  "stares at phone": "📱👀",
  "checks clock again": "⏰😩",
  "scrolls endlessly": "📱🌀",
  "accidentally likes post": "😳❤️",
  "deletes comment quickly": "🫣🗑️",
  "creeps on profile": "🕵️‍♂️📸",
  "lurks in comments": "👀💬",
  "starts typing": "💬⌨️",
  "types then stops": "✍️⏸️",
  "leaves on read": "😐📱",
  "reads message instantly": "⚡📨",
  "sends too many emojis": "😂🔥💯😩😭",
  "updates status": "🗣️🆕",
  "changes pfp": "🧑‍🎨",
  "downloads meme": "🖼️😆",
  "reposts with caption": "🔁📝",
  "makes meme": "🎨🧠",
  "gets ratioed": "📉",
  "wins argument online": "🧠🏆",
  "loses debate": "😬💢",
  "posts hot take": "🔥🤔",
  "edits post quickly": "✍️💨",
  "deletes everything": "🧹🗑️",
  "starts new account": "🆕📱",
  "logs out dramatically": "👋📴",
  "swipes left": "👈❌",
  "swipes right": "👉💘",
  "gets a match": "💘🔁",
  "sends pickup line": "😏💬",
  "gets left on seen": "😔👀",
  "tries again anyway": "😤💬",
  "gets blocked": "🚫",
  
  // Additional actions and reactions
  "puffs up cheeks": "😗",
  "makes a face": "😝",
  "sticks tongue out": "😛",
  "winks playfully": "😉",
  "licks teeth": "😋",
  "smacks lips": "😚",
  "clicks tongue disapprovingly": "🙄",
  "snaps gum": "😐",
  "chews slowly": "😬",
  "sips tea": "🍵",
  "sips dramatically": "🫖👀",
  "drinks slowly": "🧃",
  "spits out drink": "🤯🥤",
  "chokes on water": "😵💦",
  "coughs loudly": "😤",
  "bursts out laughing": "🤣",
  "cackles": "🧙‍♀️",
  "laughs maniacally": "😈",
  "laughs nervously": "😅",
  "giggles nervously": "🤭",
  "snorts": "😤",
  "screams internally": "😫",
  "screams externally": "😱",
  "shouts": "📢",
  "yells angrily": "😡",
  "howls": "🐺",
  "growls lowly": "😠",
  "huffs": "😤",
  "snarls quietly": "😾",
  "stomps foot": "😡",
  "throws a fit": "😫",
  "melts down": "🫠",
  "whimpers": "😢",
  "cries softly": "😿",
  "sobs loudly": "😭",
  "screeches": "😫",
  "wails": "😩",
  "groans": "😖",
  "moans dramatically": "🫥",
  "grumbles": "😠",
  "mutters under breath": "😤",
  "talks to self": "🧠💬",
  "mumbles": "😐",
  "grits out words": "😤",
  "stutters": "😬",
  "trails off": "💭",
  "changes subject": "🔀",
  "deflects": "🛡️",
  "redirects conversation": "🔄",
  "ghosts conversation": "👻",
  "blocks user": "🚫",
  "unfollows": "❌",
  
  // Social media & Gaming
  "streams on twitch": "🎥💜",
  "gets one viewer": "👁️",
  "talks to self on stream": "🗣️📺",
  "gets raided": "🚪👥",
  "mod bans troll": "🔨🙅",
  "chat spams pog": "🗨️🔥",
  "drops emotes": "😎🎉",
  "hits sub goal": "🎉🎯",
  "starts giveaway": "🎁🎊",
  "forgets camera on": "😳📷",
  "mic peaks": "🔊😩",
  "gets clip of the day": "✂️📽️",
  "uploads highlight": "🌟🎞️",
  "posts to YouTube": "▶️📹",
  "edits thumbnail": "🖼️✨",
  "clickbaits hard": "🪝😆",
  "gets views": "👀🔥",
  "reads comments": "💬📱",
  "regrets immediately": "😐🔙",
  "turns off replies": "🚫💬",
  
  // Additional expressions
  "chuckles to self": "😏",
  "laughs softly": "😊",
  "giggles behind hand": "🤭",
  "laughs loudly": "😂",
  "wheezes laughing": "😆",
  "loses it": "🤣",
  "wipes tear from eye": "😢",
  "tears up": "😢",
  "bawls": "😭",
  "cries laughing": "😂😭",
  "bites knuckle": "😬",
  "gnashes teeth": "😠",
  "smashes keyboard": "😤⌨️",
  "throws chair": "💺💥",
  "rages": "😡",
  "stomps away": "👣",
  "walks off": "🚶‍♂️",
  "storms out": "🌩️",
  "slams door behind": "🚪💥",
  "locks door": "🔒",
  "bars window": "🪟🔒",
  "builds wall": "🧱",
  "puts up shield": "🛡️",
  "raises defenses": "🧱🛡️",
  "hides behind wall": "🫣",
  "ducks behind cover": "🧍",
  "peeks out cautiously": "👀",
  "emerges slowly": "😶‍🌫️",
  "tiptoes": "🐾",
  "creeps slowly": "🫣",
  "sneaks in": "🕵️‍♂️",
  "sneaks out": "🕵️",
  "vanishes quietly": "🌫️",
  "disappears in silence": "🤫",
  "leaves note behind": "📝",
  "writes quickly": "✍️",
  "scribbles": "📝",
  "draws heart": "❤️",
  "writes love letter": "💌",
  "sends text": "📱",
  "spams emojis": "😍😎😂🔥",
  "types nervously": "🧑‍💻",
  "deletes message": "❌",
  "unsends": "⏪",
  "ghosts": "👻",
  "left on read": "🥲",
  "double texts": "📱📱",
  "waits for reply": "⏳",
  "refreshes chat": "🔁",
  "posts meme": "🐸",
  "shares gif": "🎞️",
  "reacts with emoji": "😆👍❤️",
  "spams reactions": "🔥🔥🔥",
  "screenshots": "📸",
  "saves pic": "💾",
  "zooms in": "🔍",
  "zooms out": "🔭",
  "enhances image": "🕵️‍♂️",
  "analyzes photo": "🧠",
  "solves puzzle": "🧩",
  "decodes message": "🔐",
  "cracks code": "🧑‍💻",
  "finds clue": "🕵️‍♀️",
  "gets idea": "💡",
  "lightbulb moment": "💡✨",
  "face lights up": "😃",
  "eyes sparkle": "✨👁️",
  "starts brainstorming": "🤯",
  "thinks really hard": "🧠💥",
  "explains quickly": "💬",
  "talks fast": "😮‍💨",
  "talks too much": "😅",
  "talks over others": "😬",
  "gets ignored": "😐",
  "gets interrupted": "😑",
  "gets cut off": "✂️",
  "shuts down": "🔇",
  "walks away silently": "🚶‍♂️😶",
  "vanishes mid sentence": "💨",
  "breaks into song": "🎤🎶",
  "starts beatboxing": "🥁",
  "plays air guitar": "🎸",
  "plays air drums": "🥁",
  "starts dancing": "💃",
  "does happy dance": "🕺",
  "breakdances": "🌀",
  "moonwalks": "🌝👣",
  "headbangs": "🤘",
  "throws hands up in joy": "🙌",
  "throws confetti": "🎊",
  "celebrates": "🎉",
  "pops champagne": "🍾",
  "makes toast": "🥂",
  "raises glass": "🍷",
  "clinks glasses": "🥂",
  "starts party": "🪩",
  "turns up volume": "🔊",
  "blasts music": "🔥🎶",
  "covers face with pillow": "😩🛏️",
  "hides under blanket": "😴🛌",
  "pretends to sleep": "🫣",
  "actually falls asleep": "😴",
  "snores loudly": "💤",
  "dreams vividly": "💭🌈",
  "has nightmare": "😱",
  "wakes up suddenly": "😳",
  "blinks sleepily": "😪",
  "yawns": "🥱",
  "stretches arms overhead": "🙆",
  "drags feet": "😩",
  "makes coffee": "☕",
  "spills coffee": "☕💥",
  "burns tongue": "🔥👅",
  "rushes out door": "🏃‍♂️🚪",
  "misses bus": "🚌💨",
  "runs late": "⏰😱",
  "curses under breath": "🤬",
  "throws bag over shoulder": "🎒",
  "slams locker": "🧰💥",
  "punches wall": "👊🧱",
  "breaks pencil": "✏️💢",
  "throws paper ball": "🗑️",
  "scribbles angrily": "✍️😠",
  "doodles": "✏️🎨",
  "zones out in class": "😴",
  "passes note": "📝👀",
  "cheats on test": "👀📝",
  "gets caught": "😳",
  "looks guilty": "😬",
  "tries to explain": "🙃",
  "begs for forgiveness": "🙏",
  "offers bribe": "💰👀",
  "gets detention": "⛓️",
  "gets grounded": "😩🏠",
  "stares at ceiling": "😶‍🌫️",
  "counts tiles": "🔢",
  "loses track of time": "⏳",
  "panics at deadline": "📆😱",
  "pulls all-nighter": "😵‍💫",
  "drinks energy drink": "⚡🥤",
  "gets caffeine crash": "🛌",
  "stares at blank screen": "🖥️😐",
  "reopens closed tab": "🔁😅",
  "downloads shady file": "😬💾",
  "regrets instantly": "😓",
  "hears weird fan noise": "🧊💻",
  "computer crashes": "💻💥",
  "files disappear": "🫥📁",
  "system reboots": "🔄💻",
  "retypes everything": "😭⌨️",
  
  // Daily struggles
  "wakes up late": "⏰🛌",
  "forgets homework": "😱📚",
  "runs out the door": "🏃🚪",
  "misses ride": "🚗💨",
  "begs for a ride": "🙏🚙",
  "takes wrong bus": "🚌😬",
  "gets dropped off": "👋🚘",
  "walks in late": "😳🚶‍♂️",
  "gets stared at": "👀😐",
  "pretends nothing happened": "😎",
  "trips over bag": "🎒💥",
  "spills books": "📚🌀",
  "papers fly everywhere": "📝💨",
  "teacher sighs": "😔👩‍🏫",
  "takes deep breath": "😮‍💨",
  "finally sits down": "😩🪑",
  "chair squeaks": "😬🪑",
  "everyone looks": "👀👥",
  "melts in seat": "🫠🪑",
  "tries to focus": "🧠👓",
  "fails instantly": "😵‍💫",
  "doodles in notebook": "🖊️🎨",
  "zones out": "🌌👁️",
  "gets called on": "🧍‍♂️🔊",
  "panics": "😰💦",
  "answers wrong": "❌😓",
  "everyone laughs": "😂😬",
  "sinks into floor": "🫠🕳️",
  "bell rings": "🔔🏃",
  "rushes out": "🏃‍♀️💨",
  "forgets bag": "😩🎒",
  "runs back": "🏃↩️",
  "bumped into someone": "🤝💥",
  "apologizes": "🙇",
  "walks away fast": "🚶‍♂️💨",
  "lunch line is long": "🍔📈",
  "forgets wallet": "💸❌",
  "asks friend to cover": "🙏💳",
  "gets weird food": "🥦😐",
  "sits with new people": "🧍‍♂️👥",
  "awkward silence": "😶🥄",
  "laughs too loud": "🤣🔊",
  "spills drink": "🥤💦",
  "food falls off tray": "🍝💥",
  "cleans mess": "🧽😞",
  "leaves early": "🏃‍♂️🕑",
  "hides in bathroom": "🚽😶",
  "scrolls on phone": "📱🌀",
  "misses next class": "⏰❌",
  "realizes mistake": "😳🤦",
  "runs to hallway": "🏃‍♂️🏫",
  "door is locked": "🚪🔒",
  "knocks awkwardly": "🚪👊",
  "class stares": "👀😐",
  "teacher opens door": "😑🚪",
  "sits in back": "🙃🪑",
  "tries to disappear": "🫥",
  "gets random partner": "👤🤝",
  "partner does nothing": "😴🧍",
  "does all the work": "🧠💻",
  "submits last minute": "🕛📩",
  "gets surprise quiz": "😱📝",
  "forgets everything": "🤯❓",
  "copies silently": "👀✏️",
  "finishes early": "⏳😎",
  "double checks answers": "🔍🧠",
  "hands in paper": "📝🙌",
  "heads outside": "🌤️🚶‍♂️",
  "sun is too bright": "😵🌞",
  "shades on": "🕶️😎",
  "sees crush": "😳❤️",
  "panics internally": "🫣🧠",
  "touches up hair": "💇‍♂️✨",
  "waves awkwardly": "👋😅",
  "pretends to text": "📱🙄",
  "walks faster": "🏃‍♂️💔",
  "enters last class": "🧑‍🏫📘",
  "finds seat in corner": "🧍‍♂️📐",
  "teacher starts video": "📺🎉",
  "lights turn off": "💡🔻",
  "tries to nap": "😪🛌",
  "friend pokes": "👈😠",
  "watches in silence": "👁️📽️",
  "video glitches": "📺💥",
  "everyone groans": "😩📢",
  "teacher gives worksheet": "📄🖊️",
  "class collectively sighs": "😮‍💨👥",
  "finishes fast": "💨🧠",
  "waits for bell": "⏰👀",
  "stares at clock": "🕒👁️",
  "time slows down": "🐌🕰️",
  "finally rings": "🔔🎉",
  "sprints out": "🏃‍♀️💨",
  "meets friend outside": "👫😌",
  "talks about day": "🗣️📅",
  "laughs at chaos": "😂💬",
  "walks to bus": "🚶‍♂️🚌",
  "rides home": "🚌🎧",
  "watches outside window": "🌆👀",
  "daydreams again": "☁️🧠",
  "gets home": "🏠🔓",
  "throws bag down": "🎒💥",
  "grabs snack": "🍪🧃",
  "flops on couch": "🛋️😩",
  "opens laptop": "💻🔛",
  "plays music": "🎶🎧",
  "scrolls aimlessly": "📱🌀",
  "forgets homework again": "😨📚",
  "panics last minute": "🕛😵",
  "rereads notes": "📓👀",
  "none of it makes sense": "🤯🔤",
  "googles everything": "🔍💻",
  "gets distracted": "🧠🛫",
  "ends up watching videos": "📹😆",
  "gets nothing done": "🫠📚",
  "decides to sleep": "🛏️😴",
  "sets 6 alarms": "⏰⏰⏰⏰⏰⏰",
  "immediately passes out": "😪💤",
  "dreams of chaos": "💤🎢",
  "wakes up confused": "😵🛌",
  "checks time": "⏰😱",
  "rushes to do it all again": "🔁🏃‍♂️☕",
  
  // Social media specific actions
  "makes fake profile": "👻",
  "gets catfished": "🎣😨",
  "flirts badly": "😬💔",
  "tries being smooth": "😎😏",
  "fails miserably": "💀",
  "blames autocorrect": "😤🔤",
  "sends accidental text": "😱📱",
  "types entire paragraph": "🧠🧾",
  "writes essay": "📝📚",
  "starts fanfic": "✍️✨",
  "adds cliffhanger": "😈📖",
  "cries over characters": "😭📚",
  "fangirls aggressively": "🥹👏",
  "ships them hard": "❤️‍🔥⛵",
  "draws fanart": "🖌️🎨",
  "gets featured": "🎉✨",
  "becomes mutuals": "🤝🫶",
  "forms online bond": "🌐❤️",
  "makes discord server": "🧃🎮",
  "posts in general chat": "💬👀",
  "mutes server": "🔕",
  "boosts server": "🚀",
  "joins voice chat": "🎧🔊",
  "forgets mic on": "😳🎤",
  "leaves VC awkwardly": "🏃🔇",
  "rages in game": "🎮😡",
  "throws controller": "🎮💥",
  "slams keyboard": "⌨️👊",
  "gets headshot": "💀🎯",
  "wins match": "🏆🔥",
  "gets MVP": "⭐💪",
  "camps corner": "🫥🔫",
  "rushes mid": "🏃🔫",
  "dies instantly": "💀",
  "top frags": "🔝🔫",
  "bottom frags": "🧍",
  "blames lag": "📶😠",
  "ping spikes": "📈📶",
  "dc's mid game": "🔌🎮",
  "reconnects miraculously": "😮🔁",
  "gets clutch win": "🤯🏆",
  "team throws": "😭👎",
  "calls GG": "✌️🎮",
  "queue dodges": "🏃❌",
  "starts ranked grind": "📈🎮",
  "tilts after 2 losses": "😤🌀",
  "takes a break": "🛌🎧",
  "comes back sweaty": "💦🔥",
  "switches mains": "🔁🎮",
  "returns to comfort pick": "🛌🎯",
  "tries new strat": "🧠🔍",
  "fails hard": "💀😂",
  "posts 'no hate pls'": "🥲💬",
  "deletes video": "🗑️📹",
  "takes break from social": "😶📵",
  "posts return video": "📹🔁",
  "fans go wild": "🥳👏",
  "haters still mad": "😤💢",
  "responds with grace": "🙏🧘",
  "starts drama": "🎭🔥",
  "becomes trending topic": "📈💬",
  "makes apology vid": "😔📹",
  "includes sad music": "🎻😢",
  "shows dog for sympathy": "🐶😇",
  "gets forgiven (sort of)": "🤷‍♂️❤️",
  "announces merch": "👕🛒",
  "sells out instantly": "💸🔥",
  "makes limited drop": "⏳🎁",
  "rebrands": "🆕🎨",
  "changes username": "✏️📛",
  "starts podcast": "🎙️🧠",
  "records first ep": "📼🎧",
  "has audio issues": "😬🎙️",
  "fixes in post": "🛠️🔊",
  "uploads anyway": "🫣",
  "gets feedback": "💬💭",
  "improves next time": "🔁📈",
  "books guest": "🎤🎉",
  "goes viral": "🌍🔥",
  "celebrates milestone": "🎉🎯",
  "thanks followers": "🙏❤️",
  "cries happy tears": "🥹😭",
  "posts emotional message": "📝💖",
  "logs off smiling": "😊📴",
  "deletes message chain": "🧹",
  "burns evidence": "🔥",
  "erases board": "🧽",
  "clears chat": "🧼",
  "shuts laptop": "💻✖️",
  "disconnects internet": "📶❌",
  "powers off phone": "📴",
  "slaps phone away": "📱💥",
  "turns off notifications": "🔕",
  "puts phone face down": "🙃",
  "locks screen": "🔒",
  "enables do not disturb": "🛑",
  
  // Modern expressions and feelings
  "brain goes brr": "🧠💨",
  "social battery dead": "🔋❌",
  "forgets how to human": "🤖❓",
  "cries but aesthetic": "😭✨",
  "wants attention but hides": "👀🫣",
  "scrolls for serotonin": "📱🧠",
  "eats snack instead of meal": "🍪🍫",
  "makes bad life choices": "😬🌀",
  "vibes through chaos": "🎧🔥",
  "wakes up tired": "🛌😵",
  "says 'I'm fine'": "🙂💔",
  "talks to self in mirror": "🪞🗣️",
  "plans life at 3am": "🌃📈",
  "overthinks everything": "🧠🔁",
  "rewatches same show": "📺🔂",
  "ghosts everyone": "👻📴",
  "replies after 3 days": "📱🕒",
  "panics when phone rings": "📞😱",
  "buys stuff online again": "🛒💸",
  "tracks package obsessively": "📦👀",
  "forgets what was ordered": "🤔📦",
  "adds to wishlist": "💭🛍️",
  "can't find charger": "🔌❌",
  "gets tangled in headphones": "🎧🪢",
  "accidentally opens front cam": "📱😳",
  "stares into void": "👁️🌌",
  "brain.exe has stopped": "🧠💥",
  "exists out of spite": "😤🫠",
  "feels everything and nothing": "😶‍🌫️💔",
  "laughs to avoid crying": "😂😭",
  "shuts down emotionally": "📴❤️",
  "floors covered in clothes": "👕🧦🌀",
  "socks never match": "🧦❓",
  "laundry pile grows sentient": "🧺🧠",
  "can't find the other shoe": "👟🚫",
  "eats cereal at midnight": "🥣🌙",
  "forgets water again": "💧❌",
  "drinks 4 coffees": "☕☕☕☕",
  "still tired": "😩🛌",
  "forgets to eat": "🍽️❌",
  "overeats suddenly": "🍕🍟🍫",
  "stomach suffers": "🤢🥴",
  "orders takeout again": "📲🍔",
  "no thoughts head empty": "🧠🚫",
  "brain full of tabs": "🧠🗂️",
  "opens 38 tabs": "🌐🧠",
  "forgets why opened browser": "🤔🖥️",
  "checks one thing ends up deep dive": "🔍🕳️",
  "gets lost in Wikipedia": "📚🌪️",
  "spends 4 hours on nothing": "⏳🫠",
  "starts cleaning, ends reminiscing": "🧹📸",
  "cries at old photos": "😢🖼️",
  "replays favorite song": "🔁🎵",
  "song ends, silence hurts": "😶🎧",
  "gets too emotionally attached": "💞😩",
  "lives in fictional world": "📖🌌",
  "wants to be main character": "🎬🌟",
  "spirals in bed": "🛏️🌀",
  "reads old messages": "💬📜",
  "regrets sending that text": "😬📱",
  "types message, deletes": "✍️❌",
  "overthinks emoji choice": "🤔😂😭",
  "sends meme instead": "📤🖼️",
  "accidentally sends wrong person": "😱📩",
  "changes username again": "🆕🪪",
  "rebrands self mentally": "🔄🧠",
  "unplugs from reality": "🔌🌍",
  "wants to disappear but cute": "🫥💖",
  "replays argument in head": "💭💢",
  "imaginary fight in shower": "🚿🥊",
  "wins every time": "🏆🧠",
  "doesn't follow own advice": "🗣️🙅",
  "googles symptoms again": "🔍😷",
  "diagnosed with doom": "💀🩺",
  "starts journal, forgets": "📓❌",
  "buys planner, doesn't plan": "📅🫠",
  "makes aesthetic notes": "🖋️🌸",
  "forgets to study": "📚😶",
  "last minute panic mode": "😰🕛",
  "studies all night": "🌙☕",
  "still fails": "😵📉",
  "asks for extension": "🙏📝",
  "ghosts professor": "👻🎓",
  "forgets to graduate": "🎓❌",
  "exists in liminal space": "🚪🌫️",
  "stands in kitchen at 2am": "🍽️🌃",
  "lights flicker dramatically": "💡⚡",
  "feels like npc": "🧍‍♂️🎮",
  "questions everything": "🤨🌌",
  "existential dread kicks in": "😨🕳️",
  "disassociates mid sentence": "🫥🗨️",
  "nervous laughter": "😅💢",
  "trauma but funny": "🤡💔",
  "jokes instead of feelings": "😂😶‍🌫️",
  "wants to hold hand": "🤝🥺",
  "wants to be held": "🫂💖",
  "longs for comfort": "🛌☁️",
  "sends 'u up?' ironically": "🕒👀",
  "hopes they reply": "📱❤️",
  "they don't": "❌📴",
  "posts sad story": "😢📸",
  "checks views immediately": "👀📊",
  "deletes in 2 mins": "🗑️😳",
  "starts healing arc": "🌱🧠",
  "relapses 4 times": "🔁😞",
  "tries again": "🛠️💪",
  "cries in car": "🚗😭",
  "laughs after crying": "😭😂",
  "messes up again": "🫠🔁",
  "survives anyway": "✨💥",
  "we go again": "🔁🏃‍♂️",
  "too tired to care": "😴🤷‍♂️",
  "hopes tomorrow's better": "☀️🙏",
  "keeps scrolling": "📱🔁",
  "maybe tomorrow": "🫥📅",
  
  // More relatable expressions
  "wants to scream into void": "😱🌌",
  "doesn't even have energy to cry": "😐💧",
  "scrolls dead-eyed": "👁️📱",
  "forgets what happiness feels like": "😶‍🌫️🫠",
  "checks notifications again": "📲👀",
  "still nothing": "🗑️🔔",
  "thinks of texting them": "🤔📱",
  "doesn't": "❌💬",
  "stares at wall": "🧍🧱",
  "blank mind full heart": "💖😶",
  "brain is buffering": "🧠⏳",
  "waiting for a sign": "👀🔮",
  "pretending it's fine": "🙂🔪",
  "laughing through pain": "😭😂",
  "talks to pet like a person": "🐶🗣️",
  "pet understands everything": "🐾🧠",
  "makes dramatic exit": "🚪💨",
  "realizes forgot phone": "📱😱",
  "walks back in less dramatic": "🚶‍♂️😐",
  "can't find matching lid": "🥣🫠",
  "stands at fridge with it open": "🧊😐",
  "finds snack, forgets what else": "🍫❓",
  "stubs toe and rethinks life": "🦶💥🧠",
  "uses phone as mirror": "📱🪞",
  "accidentally opens camera again": "📸😵",
  "forgets password": "🔒❌",
  "resets password again": "♻️🔐",
  "creates worse one": "🤡🆕",
  "resends email apology": "📨🙏",
  "overuses exclamation marks": "❗❗😅",
  "deletes whole message instead": "🗑️💬",
  "starts over": "🔁✍️",
  "never sends it": "🫥📤",
  "just vibes in parking lot": "🚗🎧",
  "overthinks casual message": "💬🧠",
  "reads too deep into emoji": "🧐😂",
  "laughs at own meme": "😆📱",
  "shows no one": "🫢🖼️",
  "plans perfect comeback": "🧠💬",
  "3 days too late": "📆😩",
  "talks to crush in head": "🧠❤️",
  "they're so nice in there": "😍🧠",
  "gaslights self into not caring": "🧠🔥❌",
  "builds entire fantasy world": "🌍🛌",
  "rehearses fake interviews": "🎤🧠",
  "fame delusions": "🌟🤡",
  "spends 3 hours doing nothing": "⏳🛋️",
  "checks horoscope": "🔮♌",
  "blames stars for mood": "💫😤",
  "refreshes feed": "🔄📲",
  "refreshes again": "🔁👀",
  "still nothing new": "😑🌐",
  "shuts laptop dramatically": "💻🔨",
  "opens again immediately": "😬💻",
  "forgets what was doing": "🤔❌",
  "reopens 12 tabs": "🌐🌀",
  "reschedules everything": "📅🔁",
  "forgets new schedule": "🧠🗑️",
  "wants a sign from universe": "🛸👁️",
  "gets nothing": "🚫🌌",
  "craves chaotic good energy": "✨🔥",
  "lives on impulse": "⚡🎲",
  "plans to fix life": "🗓️🛠️",
  "takes nap instead": "🛏️😴",
  "nap turns into coma": "⏰🧠",
  "wakes disoriented": "🛌😵‍💫",
  "no clue what day it is": "📆❓",
  "craves affection, avoids people": "🫂🚷",
  "wants to be touched but not talked to": "✋🤫",
  "reads messages, doesn't reply": "📬👀",
  "socially logs off": "📴😶",
  "turns off brain": "🔌🧠",
  "sets one alarm": "⏰😎",
  "snoozes 8 times": "😴🔁",
  "rushes in panic": "🏃‍♀️💥",
  "everything goes wrong": "🫠📉",
  "blames Mercury retrograde": "☿️🔄",
  "drinks cold coffee": "🧊☕",
  "wasn't meant to be cold": "😩🥶",
  "forgets coffee exists": "☕🫥",
  "drinks reheated regret": "🔁😞",
  "does skincare for 1 day": "🧴✨",
  "expects full transformation": "💅🪞",
  "breaks out anyway": "😫🧼",
  "never tries again": "❌🧴",
  "buys cute journal": "📔💖",
  "writes 3 pages, stops": "📝🫠",
  "starts hobby": "🧶🎯",
  "gives up after 1 attempt": "💀🎨",
  "tells everyone about it anyway": "📢🎉",
  "becomes personality for a week": "🧍🎭",
  "forgets it ever happened": "😅🚫",
  "gets obsessed randomly": "🔥👀",
  "hyperfixates for 72 hours": "🧠🔒",
  "burns out completely": "🫠💨",
  "searches 'what is wrong with me'": "🔍💔",
  "relatable tweet hits too hard": "📱💀",
  "laugh reacts instead of processing": "😂🫠",
  "saves meme for later": "🖼️📁",
  "never finds it again": "🤷‍♀️📂",
  "downloads 5 new apps": "📲🆕",
  "uses none": "❌📱",
  "phone storage full": "💾🔴",
  "deletes old photos": "📸🗑️",
  "scrolls too far": "🌀📲",
  "sees ex's post": "😐💔",
  "spirals quietly": "🧠🔄",
  "puts phone on do not disturb": "🔕🛌",
  "waits for someone to text anyway": "👀📱",
  "they don't": "🫥💔",
  "opens notes app": "📓💬",
  "writes deep thoughts": "✍️😔",
  "reads later, cringes": "😬📖",
  "deletes entire thing": "🗑️📓",
  "starts playlist": "🎶🧠",
  "every song hurts": "😢🎧",
  "keeps listening": "🔁😭",
  "creates fake scenarios": "🧠🎬",
  "narrated by Morgan Freeman": "🎙️👴",
  "wins fake award": "🏆🛌",
  "thanks imaginary fans": "👏🧠",
  "trip and pretend it was intentional": "🫣🏃‍♀️",
  "nod at stranger in hallway": "😐🙃",
  "awkward mutual nod": "😅👋",
  "walks away too fast": "🚶‍♂️💨",
  "too much eye contact": "👀🔁",
  "not enough eye contact": "🫣🙈",
  "overthinks forever": "🔁🧠",
  "remembers in shower next day": "🚿💭"
};

/**
 * Converts text enclosed in asterisks to appropriate emojis
 * @param text Text that may contain expressions in asterisks
 * @returns Text with asterisk expressions converted to emojis
 */
export function convertAsteriskTextToEmojis(text: string): string {
  // Regular expression to match text inside asterisks: *text*
  const asteriskPattern = /\*([^*]+)\*/g;
  
  return text.replace(asteriskPattern, (match, textInsideAsterisks) => {
    // Convert to lowercase for matching
    const lowerCaseText = textInsideAsterisks.toLowerCase().trim();
    
    // Check if there's a matching emoji in our map
    for (const [expression, emoji] of Object.entries(emojiMap)) {
      if (lowerCaseText.includes(expression)) {
        return emoji; // Replace with appropriate emoji
      }
    }
    
    // If no match found, keep the original text but remove asterisks
    return textInsideAsterisks;
  });
}

/**
 * Helper function to detect and preserve emojis in user input
 * This ensures emojis are not converted to text descriptions in AI responses
 * 
 * @param text The input text from the user
 * @returns Processed text with emojis preserved
 */
export function preserveUserEmojis(text: string): string {
  // We don't need to modify the text, just ensure the AI model instruction
  // is set correctly to preserve emojis as is in the response
  return text;
}

/**
 * Function to preprocess chat history to ensure emojis are preserved 
 * 
 * @param chatHistory The chat history string
 * @returns Processed chat history with emojis preserved
 */
export function preprocessChatHistory(chatHistory: string): string {
  // Make sure any emojis in the chat history are preserved
  return chatHistory;
}