import { type Character } from "@shared/characters";

// Comprehensive emoji mapping for actions and expressions found inside asterisks
// This helps convert text descriptions to actual emojis
const emojiMap: Record<string, string> = {
  // Basic emotions and actions
  "smile": "😊",
  "grin": "😁",
  "laugh": "😂",
  "joy": "😄",
  "sigh": "😔",
  "sad": "😢",
  "cry": "😢",
  "tears": "😭",
  "sob": "😭",
  "angry": "😠",
  "mad": "😡",
  "furious": "🤬",
  "frown": "🙁",
  "worried": "😟",
  "nervous": "😬",
  "anxious": "😰",
  "scared": "😨",
  "terrified": "😱",
  "confused": "😕",
  "surprised": "😮",
  "shocked": "😲",
  "amazed": "😲",
  "disappointed": "😞",
  "relieved": "😌",
  "satisfied": "😌",
  "sleepy": "😴",
  "tired": "😫",
  "exhausted": "😩",
  "yawn": "🥱",
  "blush": "😊",
  "embarrassed": "😳",
  "thinking": "🤔",
  "thoughtful": "🤔",
  "neutral": "😐",
  "indifferent": "😐",
  "rolling eyes": "🙄",
  "eye roll": "🙄",
  "wink": "😉",
  "smirk": "😏",
  "tongue": "😛",
  "tongue out": "😋",
  "drool": "🤤",
  "excited": "🤩",
  "heart eyes": "😍",
  "love": "❤️",
  "heart": "❤️",
  "thumbs up": "👍",
  "thumbs down": "👎",
  "clap": "👏",
  "shrug": "🤷",
  "face palm": "🤦",
  "facepalm": "🤦",
  "sweat": "😅",
  "sweet": "🥰",
  "hug": "🤗",
  
  // Head movements
  "nods slowly": "👍",
  "nods enthusiastically": "😀👍",
  "shakes head": "🙅‍♂️",
  "shrugs helplessly": "🤷",
  "throws hands up": "🙌",
  "slaps forehead": "🤦",
  "facepalms hard": "🤦‍♂️",
  "sighs deeply": "😮‍💨",
  "gasps audibly": "😲",
  "inhales sharply": "😧",
  "holds chest": "🫀",
  "clutches pearls": "😱",
  "stares blankly": "😐",
  "raises eyebrow": "🤨",
  "furrows brows": "😠",
  "squints slightly": "🧐",
  "narrows eyes": "😒",
  "widens eyes": "😳",
  "eyes dart around": "👀",
  "shifts uncomfortably": "😬",
  "looks around nervously": "😟",
  "bites lip": "😬",
  "taps foot": "👟",
  "bounces knee": "🦵",
  "folds arms": "😤",
  "crosses arms": "🙅‍♀️",
  "tilts head": "🤔",
  "tilts head confusedly": "😕",
  "smirks": "😏",
  "pouts": "😢",
  
  // Advanced actions
  "presses lips together": "😶",
  "grins mischievously": "😏",
  "twirls mustache": "🧐",
  "looks innocent": "😇",
  "pretends not to know": "🤥",
  "acts surprised": "😲",
  "acts offended": "😤",
  "acts clueless": "😶",
  "acts cool": "😎",
  "acts dramatic": "🎭",
  "acts suspicious": "🕵️",
  "side-eyes": "👀",
  "deadpans": "😐",
  "monologues": "🎙️",
  "narrates": "📖",
  "commentates": "🎤",
  "breaks fourth wall": "🪞",
  "narrates dramatically": "🎬",
  "voice cracks": "🫨",
  "clears throat": "😬",
  "adjusts tie": "👔",
  "adjusts hat": "🎩",
  "fixes hair": "💇",
  "reapplies makeup": "💄",
  "checks reflection": "🪞",
  "pops collar": "😎",
  "struts": "🕺",
  "poses for camera": "📸",
  "strikes pose": "💃",
  "does peace sign": "✌️",
  "throws gang sign": "🫰",
  "salutes stiffly": "🫡",
  "waves dramatically": "👋",
  "nods curtly": "🙃",
  "glances quickly": "👀",
  "squints suspiciously": "🧐",
  "glowers": "😠",
  "glances knowingly": "😏",
  "winks slyly": "😉",
  "twirls finger": "🔄",
  "cracks fingers": "✋",
  "pats back": "🤗",
  "rubs back": "💆",
  "hugs tightly": "🤗",
  "grabs hand": "✋",
  "holds hands": "🤝",
  "shakes hands": "🤝",
  
  // Phone and tech related
  "stares at phone": "📱👀",
  "checks clock again": "⏰😩",
  "scrolls endlessly": "📱🌀",
  "accidentally likes post": "😳❤️",
  "deletes comment quickly": "🫣🗑️",
  "creeps on profile": "🕵️‍♂️📸",
  "lurks in comments": "👀💬",
  "starts typing": "💬⌨️",
  "types then stops": "✍️⏸️",
  "leaves on read": "😐📱",
  "reads message instantly": "⚡📨",
  "sends too many emojis": "😂🔥💯😩😭",
  "updates status": "🗣️🆕",
  "changes pfp": "🧑‍🎨",
  "downloads meme": "🖼️😆",
  "reposts with caption": "🔁📝",
  "makes meme": "🎨🧠",
  "gets ratioed": "📉",
  "wins argument online": "🧠🏆",
  "loses debate": "😬💢",
  "posts hot take": "🔥🤔",
  "edits post quickly": "✍️💨",
  "deletes everything": "🧹🗑️",
  "starts new account": "🆕📱",
  "logs out dramatically": "👋📴",
  "swipes left": "👈❌",
  "swipes right": "👉💘",
  "gets a match": "💘🔁",
  "sends pickup line": "😏💬",
  "gets left on seen": "😔👀",
  "tries again anyway": "😤💬",
  "gets blocked": "🚫",
  
  // Additional actions and reactions
  "puffs up cheeks": "😗",
  "makes a face": "😝",
  "sticks tongue out": "😛",
  "winks playfully": "😉",
  "licks teeth": "😋",
  "smacks lips": "😚",
  "clicks tongue disapprovingly": "🙄",
  "snaps gum": "😐",
  "chews slowly": "😬",
  "sips tea": "🍵",
  "sips dramatically": "🫖👀",
  "drinks slowly": "🧃",
  "spits out drink": "🤯🥤",
  "chokes on water": "😵💦",
  "coughs loudly": "😤",
  "bursts out laughing": "🤣",
  "cackles": "🧙‍♀️",
  "laughs maniacally": "😈",
  "laughs nervously": "😅",
  "giggles nervously": "🤭",
  "snorts": "😤",
  "screams internally": "😫",
  "screams externally": "😱",
  "shouts": "📢",
  "yells angrily": "😡",
  "howls": "🐺",
  "growls lowly": "😠",
  "huffs": "😤",
  "snarls quietly": "😾",
  "stomps foot": "😡",
  "throws a fit": "😫",
  "melts down": "🫠",
  "whimpers": "😢",
  "cries softly": "😿",
  "sobs loudly": "😭",
  "screeches": "😫",
  "wails": "😩",
  "groans": "😖",
  "moans dramatically": "🫥",
  "grumbles": "😠",
  "mutters under breath": "😤",
  "talks to self": "🧠💬",
  "mumbles": "😐",
  "grits out words": "😤",
  "stutters": "😬",
  "trails off": "💭",
  "changes subject": "🔀",
  "deflects": "🛡️",
  "redirects conversation": "🔄",
  "ghosts conversation": "👻",
  "blocks user": "🚫",
  "unfollows": "❌",
  
  // Social media & Gaming
  "streams on twitch": "🎥💜",
  "gets one viewer": "👁️",
  "talks to self on stream": "🗣️📺",
  "gets raided": "🚪👥",
  "mod bans troll": "🔨🙅",
  "chat spams pog": "🗨️🔥",
  "drops emotes": "😎🎉",
  "hits sub goal": "🎉🎯",
  "starts giveaway": "🎁🎊",
  "forgets camera on": "😳📷",
  "mic peaks": "🔊😩",
  "gets clip of the day": "✂️📽️",
  "uploads highlight": "🌟🎞️",
  "posts to YouTube": "▶️📹",
  "edits thumbnail": "🖼️✨",
  "clickbaits hard": "🪝😆",
  "gets views": "👀🔥",
  "reads comments": "💬📱",
  "regrets immediately": "😐🔙",
  "turns off replies": "🚫💬",
  
  // Additional expressions
  "chuckles to self": "😏",
  "laughs softly": "😊",
  "giggles behind hand": "🤭",
  "laughs loudly": "😂",
  "wheezes laughing": "😆",
  "loses it": "🤣",
  "wipes tear from eye": "😢",
  "tears up": "😢",
  "bawls": "😭",
  "cries laughing": "😂😭",
  "bites knuckle": "😬",
  "gnashes teeth": "😠",
  "smashes keyboard": "😤⌨️",
  "throws chair": "💺💥",
  "rages": "😡",
  "stomps away": "👣",
  "walks off": "🚶‍♂️",
  "storms out": "🌩️",
  "slams door behind": "🚪💥",
  "locks door": "🔒",
  "bars window": "🪟🔒",
  "builds wall": "🧱",
  "puts up shield": "🛡️",
  "raises defenses": "🧱🛡️",
  "hides behind wall": "🫣",
  "ducks behind cover": "🧍",
  "peeks out cautiously": "👀",
  "emerges slowly": "😶‍🌫️",
  "tiptoes": "🐾",
  "creeps slowly": "🫣",
  "sneaks in": "🕵️‍♂️",
  "sneaks out": "🕵️",
  "vanishes quietly": "🌫️",
  "disappears in silence": "🤫",
  "leaves note behind": "📝",
  "writes quickly": "✍️",
  "scribbles": "📝",
  "draws heart": "❤️",
  "writes love letter": "💌",
  "sends text": "📱",
  "spams emojis": "😍😎😂🔥",
  "types nervously": "🧑‍💻",
  "deletes message": "❌",
  "unsends": "⏪",
  "ghosts": "👻",
  "left on read": "🥲",
  "double texts": "📱📱",
  "waits for reply": "⏳",
  "refreshes chat": "🔁",
  "posts meme": "🐸",
  "shares gif": "🎞️",
  "reacts with emoji": "😆👍❤️",
  "spams reactions": "🔥🔥🔥",
  "screenshots": "📸",
  "saves pic": "💾",
  "zooms in": "🔍",
  "zooms out": "🔭",
  "enhances image": "🕵️‍♂️",
  "analyzes photo": "🧠",
  "solves puzzle": "🧩",
  "decodes message": "🔐",
  "cracks code": "🧑‍💻",
  "finds clue": "🕵️‍♀️",
  "gets idea": "💡",
  "lightbulb moment": "💡✨",
  "face lights up": "😃",
  "eyes sparkle": "✨👁️",
  "starts brainstorming": "🤯",
  "thinks really hard": "🧠💥",
  "explains quickly": "💬",
  "talks fast": "😮‍💨",
  "talks too much": "😅",
  "talks over others": "😬",
  "gets ignored": "😐",
  "gets interrupted": "😑",
  "gets cut off": "✂️",
  "shuts down": "🔇",
  "walks away silently": "🚶‍♂️😶",
  "vanishes mid sentence": "💨",
  "breaks into song": "🎤🎶",
  "starts beatboxing": "🥁",
  "plays air guitar": "🎸",
  "plays air drums": "🥁",
  "starts dancing": "💃",
  "does happy dance": "🕺",
  "breakdances": "🌀",
  "moonwalks": "🌝👣",
  "headbangs": "🤘",
  "throws hands up in joy": "🙌",
  "throws confetti": "🎊",
  "celebrates": "🎉",
  "pops champagne": "🍾",
  "makes toast": "🥂",
  "raises glass": "🍷",
  "clinks glasses": "🥂",
  "starts party": "🪩",
  "turns up volume": "🔊",
  "blasts music": "🔥🎶",
  "covers face with pillow": "😩🛏️",
  "hides under blanket": "😴🛌",
  "pretends to sleep": "🫣",
  "actually falls asleep": "😴",
  "snores loudly": "💤",
  "dreams vividly": "💭🌈",
  "has nightmare": "😱",
  "wakes up suddenly": "😳",
  "blinks sleepily": "😪",
  "yawns": "🥱",
  "stretches arms overhead": "🙆",
  "drags feet": "😩",
  "makes coffee": "☕",
  "spills coffee": "☕💥",
  "burns tongue": "🔥👅",
  "rushes out door": "🏃‍♂️🚪",
  "misses bus": "🚌💨",
  "runs late": "⏰😱",
  "curses under breath": "🤬",
  "throws bag over shoulder": "🎒",
  "slams locker": "🧰💥",
  "punches wall": "👊🧱",
  "breaks pencil": "✏️💢",
  "throws paper ball": "🗑️",
  "scribbles angrily": "✍️😠",
  "doodles": "✏️🎨"
};

/**
 * Converts text enclosed in asterisks to appropriate emojis
 * @param text Text that may contain expressions in asterisks
 * @returns Text with asterisk expressions converted to emojis
 */
export function convertAsteriskTextToEmojis(text: string): string {
  // Regular expression to match text inside asterisks: *text*
  const asteriskPattern = /\*([^*]+)\*/g;
  
  return text.replace(asteriskPattern, (match, textInsideAsterisks) => {
    // Convert to lowercase for matching
    const lowerCaseText = textInsideAsterisks.toLowerCase().trim();
    
    // Check if there's a matching emoji in our map
    for (const [expression, emoji] of Object.entries(emojiMap)) {
      if (lowerCaseText.includes(expression)) {
        return emoji; // Replace with appropriate emoji
      }
    }
    
    // If no match found, keep the original text but remove asterisks
    return textInsideAsterisks;
  });
}