// Emoji mappings for expressions
// Maps text expressions to their emoji equivalents
export const expressionToEmojiMap: Record<string, string> = {
  // Basic expressions
  "*nods*": "👍",
  "*shakes head*": "🙅",
  "*laughs*": "😂",
  "*laughs softly*": "😊",
  "*laughs nervously*": "😅",
  "*giggles*": "😄",
  "*snorts*": "😆",
  "*smirks*": "😏",
  "*grins*": "😁",
  "*grins sheepishly*": "😅",
  "*smiles warmly*": "🙂",
  "*smiles sadly*": "😔",
  "*smiles weakly*": "😕",
  "*frowns*": "☹️",
  "*pouts*": "😞",
  "*gasps*": "😯",
  "*gasps loudly*": "😲",
  "*sighs*": "😔",
  "*sniffs*": "🤧",
  "*sneezes*": "🤧",
  "*coughs*": "😷",
  "*yawns*": "🥱",
  "*cries*": "😢",
  "*sobs*": "😭",
  "*wails*": "😩",
  "*whimpers*": "😟",
  "*gulps*": "😰",
  "*winces*": "😣",
  "*grimaces*": "😬",
  "*groans*": "😩",
  "*moans*": "😫",
  "*screams*": "😱",
  "*shrieks*": "😨",
  "*gasps dramatically*": "😧",
  "*stares*": "👀",
  "*stares blankly*": "😐",
  "*stares in shock*": "😲",
  "*narrows eyes*": "😒",
  "*glares*": "😠",
  "*squints*": "😑",
  "*rolls eyes*": "🙄",
  "*raises eyebrow*": "🤨",
  "*arches brow*": "🤔",
  "*tilts head*": "🤔",
  "*cocks head*": "🧐",
  "*nods slowly*": "👌",
  "*shrugs*": "🤷",
  "*facepalms*": "🤦",
  "*holds head in hands*": "🤯",
  "*rubs temples*": "😣",
  "*covers face*": "😖",
  "*scrunches up face*": "😕",
  "*looks confused*": "😕",
  "*looks surprised*": "😮",
  "*looks scared*": "😨",
  "*looks amused*": "😄",
  "*looks unimpressed*": "😑",
  "*looks skeptical*": "🧐",
  "*looks annoyed*": "😒",
  "*looks angry*": "😠",
  "*looks disappointed*": "😞",
  "*looks hopeful*": "🤞",
  "*looks excited*": "😃",
  "*looks embarrassed*": "😳",
  "*blushes*": "😊",
  "*turns red*": "😳",
  "*giggles nervously*": "😅",
  "*covers mouth*": "🤭",
  "*waves*": "👋",
  "*waves shyly*": "👋",
  "*gives thumbs up*": "👍",
  "*gives thumbs down*": "👎",
  "*claps*": "👏",
  "*cheers*": "🎉",
  "*jumps*": "🕴️",
  "*dances*": "💃",
  "*bows*": "🙇",
  "*salutes*": "🫡",
  "*points*": "👉",
  "*points at self*": "🙋",
  "*raises hand*": "✋",
  "*lowers hand*": "🤚",
  "*holds up hand*": "✋",
  "*crosses arms*": "😒",
  "*folds arms*": "😑",
  "*puts hands on hips*": "😤",
  "*shrugs helplessly*": "🤷",
  "*nods eagerly*": "😃",
  "*nods solemnly*": "😔",
  "*shakes head slowly*": "😞",
  "*taps foot*": "🦶",
  "*stomps*": "😠",
  "*paces*": "🧍‍♂️",
  "*sits down*": "🪑",
  "*stands up*": "🧍",
  "*leans back*": "😌",
  "*leans forward*": "🧐",
  "*tilts head in confusion*": "🤔",
  "*fidgets*": "🫨",
  "*bites lip*": "😬",
  "*chews nails*": "😬",
  "*scratches head*": "🤷",
  "*rubs neck*": "😓",
  "*looks away*": "😳",
  "*avoids eye contact*": "🙈",
  "*stares at floor*": "😞",
  
  // Additional expressions
  "*grovels*": "🙇",
  "*pleads*": "🥺",
  "*begs*": "🙏",
  "*prays*": "🙏",
  "*meditates*": "🧘",
  "*zones out*": "💤",
  "*daydreams*": "💭",
  "*spaces out*": "😶‍🌫️",
  "*snaps out of it*": "😳",
  "*blanks out*": "😐",
  "*looks bored*": "😒",
  "*taps fingers*": "🫰",
  "*presses lips together*": "😶",
  "*grins mischievously*": "😏",
  "*twirls mustache*": "🧐",
  "*looks innocent*": "😇",
  "*pretends not to know*": "🤥",
  "*acts surprised*": "😲",

  // Common text expressions
  "*sigh*": "😔",
  "*smile*": "🙂",
  "*laugh*": "😂",
  "*crying*": "😢",
  "*blush*": "😊",
  "*happy*": "😄",
  "*sad*": "😔",
  "*angry*": "😠",
  "*confused*": "😕",
  "*shocked*": "😲",
  "*thumbs up*": "👍",
  "*thumbs down*": "👎",
  "*ok*": "👌",
  "*yes*": "✅",
  "*no*": "❌",
  "*hug*": "🤗",
  "*wave*": "👋",
  "*shrug*": "🤷",
  "*eye roll*": "🙄",
  "*wink*": "😉",
  "*facepalm*": "🤦",
};

// Function to replace text expressions with emojis
export function replaceExpressionsWithEmojis(text: string): string {
  let result = text;
  
  // First, handle the case where expressions are wrapped with asterisks
  for (const [expression, emoji] of Object.entries(expressionToEmojiMap)) {
    // Replace the exact expression (with asterisks)
    const regex = new RegExp(expression.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g');
    result = result.replace(regex, emoji);
  }
  
  return result;
}

// Function to preprocess user message to preserve emojis
export function preserveEmojis(text: string): string {
  return text; // Already preserved as-is since they're Unicode characters
}