/**
 * Emoji mappings for daily life and routine expressions
 * This file contains mappings between text expressions and corresponding emojis
 * for everyday situations, school life, and common activities.
 */

export const dailyLifeExpressions: Record<string, string> = {
  // Morning/waking up
  "wakes up late": "⏰🛌",
  "wakes up tired": "🛌😵",
  "checks time": "⏰😱",
  "sets 6 alarms": "⏰⏰⏰⏰⏰⏰",
  "sets one alarm": "⏰😎",
  "snoozes 8 times": "😴🔁",
  "immediately passes out": "😪💤",
  "dreams vividly": "💭🌈",
  "has nightmare": "😱",
  "wakes up confused": "😵🛌",
  
  // School/work life
  "forgets homework": "😱📚",
  "runs out the door": "🏃🚪",
  "misses ride": "🚗💨",
  "begs for a ride": "🙏🚙",
  "takes wrong bus": "🚌😬",
  "gets dropped off": "👋🚘",
  "walks in late": "😳🚶‍♂️",
  "gets stared at": "👀😐",
  "pretends nothing happened": "😎",
  "trips over bag": "🎒💥",
  "spills books": "📚🌀",
  "papers fly everywhere": "📝💨",
  "teacher sighs": "😔👩‍🏫",
  "finally sits down": "😩🪑",
  "chair squeaks": "😬🪑",
  "everyone looks": "👀👥",
  "melts in seat": "🫠🪑",
  "tries to focus": "🧠👓",
  "fails instantly": "😵‍💫",
  "doodles in notebook": "🖊️🎨",
  "zones out": "🌌👁️",
  "gets called on": "🧍‍♂️🔊",
  "panics": "😰💦",
  "answers wrong": "❌😓",
  "everyone laughs": "😂😬",
  "sinks into floor": "🫠🕳️",
  "bell rings": "🔔🏃",
  "rushes out": "🏃‍♀️💨",
  "forgets bag": "😩🎒",
  "runs back": "🏃↩️",
  "bumped into someone": "🤝💥",
  "apologizes": "🙇",
  "walks away fast": "🚶‍♂️💨",
  
  // Food and meals
  "lunch line is long": "🍔📈",
  "forgets wallet": "💸❌",
  "asks friend to cover": "🙏💳",
  "gets weird food": "🥦😐",
  "sits with new people": "🧍‍♂️👥",
  "awkward silence": "😶🥄",
  "laughs too loud": "🤣🔊",
  "spills drink": "🥤💦",
  "food falls off tray": "🍝💥",
  "cleans mess": "🧽😞",
  "leaves early": "🏃‍♂️🕑",
  "eats snack instead of meal": "🍪🍫",
  "eats cereal at midnight": "🥣🌙",
  "forgets water again": "💧❌",
  "drinks 4 coffees": "☕☕☕☕",
  "still tired": "😩🛌",
  "forgets to eat": "🍽️❌",
  "overeats suddenly": "🍕🍟🍫",
  "stomach suffers": "🤢🥴",
  "orders takeout again": "📲🍔",
  "stands in kitchen at 2am": "🍽️🌃",
  "stands at fridge with it open": "🧊😐",
  "finds snack, forgets what else": "🍫❓",
  "stubs toe and rethinks life": "🦶💥🧠",
  "drinks cold coffee": "🧊☕",
  "wasn't meant to be cold": "😩🥶",
  "forgets coffee exists": "☕🫥",
  "drinks reheated regret": "🔁😞",
  
  // Bathroom hideouts
  "hides in bathroom": "🚽😶",
  "door is locked": "🚪🔒",
  "knocks awkwardly": "🚪👊",
  "class stares": "👀😐",
  "teacher opens door": "😑🚪",
  "sits in back": "🙃🪑",
  "tries to disappear": "🫥",
  
  // Group work
  "gets random partner": "👤🤝",
  "partner does nothing": "😴🧍",
  "does all the work": "🧠💻",
  "submits last minute": "🕛📩",
  "gets surprise quiz": "😱📝",
  "forgets everything": "🤯❓",
  "copies silently": "👀✏️",
  "finishes early": "⏳😎",
  "double checks answers": "🔍🧠",
  "hands in paper": "📝🙌",
  
  // School hallway interactions
  "heads outside": "🌤️🚶‍♂️",
  "sun is too bright": "😵🌞",
  "shades on": "🕶️😎",
  "sees crush": "😳❤️",
  "panics internally": "🫣🧠",
  "fixes hair": "💇‍♂️✨",
  "waves awkwardly": "👋😅",
  "gets ignored": "😐🧊",
  "pretends to text": "📱🙄",
  "walks faster": "🏃‍♂️💔",
  "enters last class": "🧑‍🏫📘",
  "finds seat in corner": "🧍‍♂️📐",
  
  // Classroom activities
  "teacher starts video": "📺🎉",
  "lights turn off": "💡🔻",
  "tries to nap": "😪🛌",
  "friend pokes": "👈😠",
  "watches in silence": "👁️📽️",
  "video glitches": "📺💥",
  "everyone groans": "😩📢",
  "teacher gives worksheet": "📄🖊️",
  "class collectively sighs": "😮‍💨👥",
  "finishes fast": "💨🧠",
  "waits for bell": "⏰👀",
  "stares at clock": "🕒👁️",
  "time slows down": "🐌🕰️",
  "finally rings": "🔔🎉",
  "sprints out": "🏃‍♀️💨",
  
  // After school
  "meets friend outside": "👫😌",
  "talks about day": "🗣️📅",
  "laughs at chaos": "😂💬",
  "walks to bus": "🚶‍♂️🚌",
  "rides home": "🚌🎧",
  "watches outside window": "🌆👀",
  "daydreams again": "☁️🧠",
  "gets home": "🏠🔓",
  "throws bag down": "🎒💥",
  "grabs snack": "🍪🧃",
  "flops on couch": "🛋️😩",
  "opens laptop": "💻🔛",
  "plays music": "🎶🎧",
  
  // Homework struggles
  "forgets homework again": "😨📚",
  "panics last minute": "🕛😵",
  "rereads notes": "📓👀",
  "none of it makes sense": "🤯🔤",
  "googles everything": "🔍💻",
  "gets distracted": "🧠🛫",
  "ends up watching videos": "📹😆",
  "gets nothing done": "🫠📚",
  "decides to sleep": "🛏️😴",
  "makes bad life choices": "😬🌀",
  "dreams of chaos": "💤🎢",
  "rushes to do it all again": "🔁🏃‍♂️☕",
  
  // Cleanliness and organization
  "floors covered in clothes": "👕🧦🌀",
  "socks never match": "🧦❓",
  "laundry pile grows sentient": "🧺🧠",
  "can't find the other shoe": "👟🚫",
  "starts cleaning, ends reminiscing": "🧹📸",
  "does skincare for 1 day": "🧴✨",
  "expects full transformation": "💅🪞",
  "breaks out anyway": "😫🧼",
  "never tries again": "❌🧴",
  "buys cute journal": "📔💖",
  "writes 3 pages, stops": "📝🫠",
  
  // Hobbies and commitments
  "starts hobby": "🧶🎯",
  "gives up after 1 attempt": "💀🎨",
  "tells everyone about it anyway": "📢🎉",
  "becomes personality for a week": "🧍🎭",
  "forgets it ever happened": "😅🚫",
  "gets obsessed randomly": "🔥👀",
  "hyperfixates for 72 hours": "🧠🔒",
  "burns out completely": "🫠💨",
  "takes break": "🛌🎧",
};