/**
 * Emoji mappings for emotional reactions
 * This file contains mappings between text expressions and corresponding emojis
 * for emotional reactions like laughing, crying, etc.
 */

export const emotionalReactions: Record<string, string> = {
  // Laughter reactions
  "laughs": "😂",
  "laugh": "😂",
  "laughs softly": "😊",
  "laughs nervously": "😅",
  "laughs loudly": "😂",
  "laughs maniacally": "😈",
  "laughs evilly": "😈",
  "laughs at own joke": "😅",
  "laughs wheezing": "😆",
  "loses it": "🤣",
  "cries laughing": "😂😭",
  "bursts out laughing": "🤣",
  "giggles": "😄",
  "giggles nervously": "😅",
  "giggles uncontrollably": "🤭",
  "giggles behind hand": "🤭",
  "snorts": "😆",
  "snickers": "😏",
  "chuckles": "😄",
  "chuckles dryly": "😒",
  "chuckles darkly": "😏",
  "chuckles awkwardly": "😅",
  "chuckles to self": "😏",
  "wheezes": "😤",
  "wheezes laughing": "😆",
  "cackles": "😆",
  "stifles laugh": "😆",
  "snorts loudly": "🐽",
  "chortles": "😄",
  
  // Crying and sadness
  "cries": "😢",
  "cry": "😢",
  "cries softly": "😿",
  "tears": "😢",
  "tears up": "😢",
  "wipes tear from eye": "😢",
  "sobs": "😭",
  "sobs loudly": "😭",
  "bawls": "😭",
  "whimpers": "😟",
  "wails": "😩",
  "sad": "😔",
  "sadly": "😔",
  
  // Anger and frustration
  "angry": "😠",
  "angrily": "😠",
  "glares": "😠",
  "glares at": "😠",
  "snarls": "😠",
  "growls": "😡",
  "glowers": "😠",
  "scowls": "😠",
  "rages": "😡",
  "shakes with rage": "😡",
  "yells angrily": "😡",
  "huffs": "😤",
  "snarls quietly": "😾",
  "grumbles": "😠",
  "throws a fit": "😫",
  "shakes fist": "👊",
  "slams fist": "👊",
  "punches air": "🥊",
  "punches wall": "👊🧱",
  "kicks": "🦵",
  "air kicks": "🦵",
  
  // Surprise and shock
  "gasps": "😯",
  "gasps loudly": "😲",
  "gasps audibly": "😲",
  "gasps dramatically": "😧",
  "shock": "😲",
  "shocked": "😲",
  "surprise": "😮",
  "surprised": "😮",
  "inhales sharply": "😯",
  "screams": "😱",
  "screams internally": "😫",
  "screams externally": "😱",
  "shrieks": "😨",
  "screeches": "😫",
  "jumps back": "😨",
  "flinches": "😖",
  "spits out drink": "🤯🥤",
  "clutches pearls": "😱",
  "jaw drop": "😱",
  
  // Fear and anxiety
  "nervous": "😅",
  "nervously": "😅",
  "gulps": "😰",
  "gulps nervously": "😰",
  "sweats": "😓",
  "starts sweating": "🫣",
  "hyperventilates": "😰",
  "panics": "😱",
  "trembles": "😰",
  "shivers": "🥶",
  "fidgets": "🫨",
  "fidgeting": "🫨",
  
  // Pain and discomfort
  "winces": "😣",
  "grimaces": "😬",
  "coughs": "😷",
  "coughs nervously": "😬",
  "sneezes": "🤧",
  "sniffs": "🤧",
  "groans": "😩",
  "groans loudly": "😩",
  "moans": "😫",
  "moans dramatically": "🫥",
  "grits out words": "😤",
  "stutters": "😬",
  
  // Thoughtfulness and contemplation
  "thinking": "🤔",
  "thinks": "🤔",
  "thoughtful": "🤔",
  "ponders": "🤔",
  "thinks really hard": "🧠💥",
  "gets idea": "💡",
  "lightbulb moment": "💡✨",
  "starts brainstorming": "🤯",
  "scratches chin": "🤨",
  "strokes beard": "🧔",
  "zones out": "💤",
  "daydreams": "💭",
  "spaces out": "😶‍🌫️",
  "blanks out": "😐",
  
  // Tiredness and exhaustion
  "yawn": "🥱",
  "yawns": "🥱",
  "sleepy": "😴",
  "sighs": "😔",
  "sighs deeply": "😮‍💨",
  "takes deep breath": "😮‍💨",
  "exhales slowly": "😤",
  "stretches": "😪",
  "stretches arms overhead": "🙆",
};