/**
 * Emoji mappings for facial expressions
 * This file contains mappings between text expressions and corresponding emojis
 * for facial expressions like smiling, frowning, etc.
 */

export const facialExpressions: Record<string, string> = {
  // Basic expressions
  "smiles": "😊",
  "smile": "😊",
  "smiles widely": "😄",
  "smiles warmly": "🙂",
  "smiles sadly": "😔",
  "smiles weakly": "😕",
  "grins": "😁",
  "grin": "😁",
  "grins sheepishly": "😅",
  "grins mischievously": "😏",
  "frowns": "☹️",
  "frown": "☹️",
  "pouts": "😞",
  "pout": "😞",
  "blushes": "😊",
  "blush": "😊",
  "turns red": "😳",
  
  // Eyes and eyebrows
  "raises eyebrow": "🤨",
  "arches brow": "🤔",
  "furrows brows": "😠",
  "widens eyes": "😳",
  "narrows eyes": "😒",
  "eyes widen": "👀",
  "eyes sparkle": "✨👁️",
  "eyes dart around": "👀",
  "stares": "👀",
  "stares blankly": "😐",
  "stares in shock": "😲",
  "stares at floor": "😞",
  "stares into void": "🌀",
  "squints": "😑",
  "squints slightly": "🧐",
  "squints in disbelief": "😑",
  "rolls eyes": "🙄",
  "blinks": "😐",
  "blinks sleepily": "😪",
  "closes eyes": "🙈",
  "opens eyes slowly": "👁️",
  
  // Mouth movements
  "bites lip": "😬",
  "licks lips": "😋",
  "puckers lips": "😚",
  "makes kissy face": "😘",
  "sticks out tongue": "😛",
  "presses lips together": "😶",
  "smacks lips": "😚",
  "puffs cheeks": "😗",
  "puffs up cheeks": "😗",
  "blows out air": "😤",
  "grits teeth": "😣",
  "bares teeth": "😬",
  "gnashes teeth": "😠",
  "chews slowly": "😬",
  "chews nails": "😬",
  
  // Facial combinations
  "scrunches up face": "😕",
  "makes a face": "😖",
  "pulls a face": "😝",
  "looks confused": "😕",
  "looks surprised": "😮",
  "looks scared": "😨",
  "looks amused": "😄",
  "looks unimpressed": "😑",
  "looks skeptical": "🧐",
  "looks annoyed": "😒",
  "looks angry": "😠",
  "looks disappointed": "😞",
  "looks hopeful": "🤞",
  "looks excited": "😃",
  "looks embarrassed": "😳",
  "looks proud": "😌",
  "looks downcast": "😢",
  "looks thoughtful": "🤔",
  "looks bored": "😒",
  "looks innocent": "😇",
  "looks stunned": "😲",
  "face lights up": "😃",
  
  // Head movements
  "tilts head": "🤔",
  "tilts head confusedly": "😕",
  "tilts head in confusion": "🤔",
  "tilts head back": "😤",
  "cocks head": "🧐",
  "hangs head": "😞",
  "throws back head laughing": "😂",
  "nods": "👍",
  "nods slowly": "👍",
  "nods eagerly": "😃",
  "nods enthusiastically": "😀👍",
  "nods solemnly": "😔",
  "shakes head": "🙅",
  "shakes head slowly": "😞",
};