/**
 * Emoji mappings for physical gestures and body movements
 * This file contains mappings between text expressions and corresponding emojis
 * for gestures, postures, and physical actions.
 */

export const gesturesAndMovements: Record<string, string> = {
  // Hand gestures
  "waves": "👋",
  "wave": "👋",
  "waves shyly": "👋",
  "holds out hand": "✋",
  "holds up hand": "✋",
  "raises hand": "✋",
  "lowers hand": "🤚",
  "reaches out": "✋",
  "holds out hand": "✋",
  "points": "👉",
  "points at self": "🙋",
  "gives thumbs up": "👍",
  "thumbs up": "👍",
  "gives thumbs down": "👎",
  "thumbs down": "👎",
  "snaps fingers": "🫰",
  "snaps fingers sassily": "🧚‍♀️",
  "cracks knuckles": "👐",
  "claps": "👏",
  "high fives": "🙌",
  "fist bumps": "👊",
  "fist pump": "👊",
  "makes heart shape": "❤️",
  "crosses fingers": "🤞",
  "crosses fingers behind back": "🤞",
  "makes peace sign": "✌️",
  "victory sign": "✌️",
  "peace sign": "✌️",
  "does finger guns": "🤠",
  "throws hands up": "🙌",
  "throws hands up in joy": "🙌",
  "gestures wildly": "🗯️",
  "throws arms around": "🤗",
  "pulls away": "🙅",
  "pushes away": "✋",
  "nudges": "🤏",
  "elbows gently": "🫸",
  "pokes": "👉",
  "tickles": "😜",
  "taps fingers": "🫰",
  "drums fingers": "🥁",
  
  // Arm movements
  "crosses arms": "😒",
  "folds arms": "😑",
  "hugs": "🤗",
  "hugs tightly": "🤗",
  "puts hands on hips": "😤",
  "shrugs": "🤷",
  "shrugs helplessly": "🤷",
  "scratches head": "🤷",
  "scratches arm": "🤔",
  "scratches back": "🧍‍♂️",
  "rubs temples": "😣",
  "rubs neck": "😓",
  "rubs back": "💆",
  "rubs face": "🫠",
  "rubs eyes": "😫",
  "scratches chin": "🤨",
  "strokes beard": "🧔",
  "rolls shoulders": "🧍",
  "cracks neck": "💢",
  "covers face": "😖",
  "covers mouth": "🤭",
  "covers mouth in shock": "😮",
  "covers ears": "🙉",
  "covers eyes": "🙈",
  "covers nose": "🤧",
  "face palms": "🤦",
  "facepalms": "🤦",
  "facepalms hard": "🤦‍♂️",
  "slaps forehead": "🤦",
  "holds head in hands": "🤯",
  "holds chest": "🫀",
  
  // Leg movements
  "taps foot": "🦶",
  "stomps": "😠",
  "stomps foot": "😡",
  "stomps away": "👣",
  "kicks": "🦵",
  "bounces foot": "🦶",
  "bounces knee": "🦵",
  "crosses legs": "🧍‍♂️",
  
  // Body positions and postures
  "sits down": "🪑",
  "stands up": "🧍",
  "leans back": "😌",
  "leans forward": "🧐",
  "leans on wall": "🧍‍♂️",
  "leans over": "👀",
  "leans in close": "🫣",
  "backs away": "😳",
  "paces": "🧍‍♂️",
  "walks off": "🚶‍♂️",
  "walks away silently": "🚶‍♂️😶",
  "storms out": "🌩️",
  "runs away": "🏃",
  "runs in circles": "🔁",
  "jumps": "🕴️",
  "jumps back": "😨",
  "bows": "🙇",
  "salutes": "🫡",
  "salutes stiffly": "🫡",
  "salutes sarcastically": "😏",
  "fidgets": "🫨",
  "shifts uncomfortably": "😬",
  "looks around nervously": "😟",
  "looks away": "😳",
  "avoids eye contact": "🙈",
  "glances away": "😶",
  "glances nervously": "😬",
  "glances sideways": "👀",
  "glances knowingly": "😏",
  "looks around": "👀",
  "peeks": "🙈",
  "peeks out cautiously": "👀",
  "ducks": "🙇‍♂️",
  "ducks behind cover": "🧍",
  
  // Movement types
  "tiptoes": "🐾",
  "creeps slowly": "🫣",
  "sneaks in": "🕵️‍♂️",
  "sneaks out": "🕵️",
  "creeps": "👣",
  "lurks": "👀",
  "struts": "🕺",
  "dances": "💃",
  "does happy dance": "🕺",
  "breakdances": "🌀",
  "moonwalks": "🌝👣",
  "headbangs": "🤘",
  "does twirl": "💃",
  "spins": "🌀",
  
  // Specialized gestures
  "adjusts tie": "👔",
  "adjusts hat": "🎩",
  "fixes hair": "💇",
  "adjusts glasses": "🤓",
  "pops collar": "😎",
  "reapplies makeup": "💄",
  "checks reflection": "🪞",
  "flips hair": "💁‍♀️",
  "twirls hair": "💁",
  "tugs at sleeve": "🧥",
  "twirls mustache": "🧐",
};