/**
 * Emoji mappings for mental states and internal experiences
 * This file contains mappings between text expressions and corresponding emojis
 * for feelings, thoughts, and cognitive/emotional states.
 */

export const mentalStateExpressions: Record<string, string> = {
  // Mental states
  "brain goes brr": "🧠💨",
  "social battery dead": "🔋❌",
  "forgets how to human": "🤖❓",
  "cries but aesthetic": "😭✨",
  "wants attention but hides": "👀🫣",
  "vibes through chaos": "🎧🔥",
  "says 'I'm fine'": "🙂💔",
  "talks to self in mirror": "🪞🗣️",
  "plans life at 3am": "🌃📈",
  "overthinks everything": "🧠🔁",
  "rewatches same show": "📺🔂",
  "forgets what happiness feels like": "😶‍🌫️🫠",
  "blank mind full heart": "💖😶",
  "brain is buffering": "🧠⏳",
  "waiting for a sign": "👀🔮",
  "pretending it's fine": "🙂🔪",
  "laughing through pain": "😭😂",
  "no thoughts head empty": "🧠🚫",
  "brain full of tabs": "🧠🗂️",
  "opens 38 tabs": "🌐🧠",
  "forgets why opened browser": "🤔🖥️",
  "checks one thing ends up deep dive": "🔍🕳️",
  "gets lost in Wikipedia": "📚🌪️",
  "spends 4 hours on nothing": "⏳🫠",
  
  // Overthinking and rumination
  "stares at wall": "🧍🧱",
  "stares into void": "👁️🌌",
  "overthinks casual message": "💬🧠",
  "reads too deep into emoji": "🧐😂",
  "plans perfect comeback": "🧠💬",
  "3 days too late": "📆😩",
  "talks to crush in head": "🧠❤️",
  "they're so nice in there": "😍🧠",
  "gaslights self into not caring": "🧠🔥❌",
  "builds entire fantasy world": "🌍🛌",
  "rehearses fake interviews": "🎤🧠",
  "fame delusions": "🌟🤡",
  "wants to scream into void": "😱🌌",
  "doesn't even have energy to cry": "😐💧",
  "overanalyzes everything": "🧐🔍",
  "creates fake scenarios": "🧠🎬",
  "narrated by Morgan Freeman": "🎙️👴",
  "wins fake award": "🏆🛌",
  "thanks imaginary fans": "👏🧠",
  
  // Self-doubt and anxiety
  "searches 'what is wrong with me'": "🔍💔",
  "relatable tweet hits too hard": "📱💀",
  "laugh reacts instead of processing": "😂🫠",
  "trip and pretend it was intentional": "🫣🏃‍♀️",
  "nod at stranger in hallway": "😐🙃",
  "awkward mutual nod": "😅👋",
  "walks away too fast": "🚶‍♂️💨",
  "too much eye contact": "👀🔁",
  "not enough eye contact": "🫣🙈",
  "overthinks forever": "🔁🧠",
  "remembers in shower next day": "🚿💭",
  "panics internally": "🫣🧠",
  "spirals in bed": "🛏️🌀",
  "reads old messages": "💬📜",
  "regrets sending that text": "😬📱",
  "types message, deletes": "✍️❌",
  "overthinks emoji choice": "🤔😂😭",
  "sends meme instead": "📤🖼️",
  "accidentally sends wrong person": "😱📩",
  "changes username again": "🆕🪪",
  "rebrands self mentally": "🔄🧠",
  
  // Existential thoughts
  "unplugs from reality": "🔌🌍",
  "wants to disappear but cute": "🫥💖",
  "replays argument in head": "💭💢",
  "imaginary fight in shower": "🚿🥊",
  "wins every time": "🏆🧠",
  "doesn't follow own advice": "🗣️🙅",
  "googles symptoms again": "🔍😷",
  "diagnosed with doom": "💀🩺",
  "starts journal, forgets": "📓❌",
  "buys planner, doesn't plan": "📅🫠",
  "makes aesthetic notes": "🖋️🌸",
  "questions everything": "🤨🌌",
  "existential dread kicks in": "😨🕳️",
  "screams internally": "😱🔇",
  "disassociates mid sentence": "🫥🗨️",
  "nervous laughter": "😅💢",
  "trauma but funny": "🤡💔",
  "jokes instead of feelings": "😂😶‍🌫️",
  
  // Loneliness and connection
  "wants to be touched but not talked to": "✋🤫",
  "wants to hold hand": "🤝🥺",
  "wants to be held": "🫂💖",
  "longs for comfort": "🛌☁️",
  "sends 'u up?' ironically": "🕒👀",
  "hopes they reply": "📱❤️",
  "they don't": "❌📴",
  "posts sad story": "😢📸",
  "checks views immediately": "👀📊",
  "deletes in 2 mins": "🗑️😳",
  "starts healing arc": "🌱🧠",
  "relapses 4 times": "🔁😞",
  "tries again": "🛠️💪",
  "cries in car": "🚗😭",
  "laughs after crying": "😭😂",
  "messes up again": "🫠🔁",
  "survives anyway": "✨💥",
  "we go again": "🔁🏃‍♂️",
  "too tired to care": "😴🤷‍♂️",
  "hopes tomorrow's better": "☀️🙏",
  "keeps scrolling": "📱🔁",
  "maybe tomorrow": "🫥📅",
  "craves chaotic good energy": "✨🔥",
  "lives on impulse": "⚡🎲",
  "plans to fix life": "🗓️🛠️",
  "takes nap instead": "🛏️😴",
  "nap turns into coma": "⏰🧠",
  "wakes up confused": "🛌😵‍💫",
  "no clue what day it is": "📆❓",
  "craves affection, avoids people": "🫂🚷",
  
  // Neurodivergent experiences
  "feels like npc": "🧍‍♂️🎮",
  "lights flicker dramatically": "💡⚡",
  "blames Mercury retrograde": "☿️🔄",
  "opens notes app": "📓💬",
  "writes deep thoughts": "✍️😔",
  "reads later, cringes": "😬📖",
  "deletes entire thing": "🗑️📓",
  "talks to pet like a person": "🐶🗣️",
  "pet understands everything": "🐾🧠",
  "makes dramatic exit": "🚪💨",
  "realizes forgot phone": "📱😱",
  "walks back in less dramatic": "🚶‍♂️😐",
  "exists in liminal space": "🚪🌫️",
  "exists out of spite": "😤🫠",
  "feels everything and nothing": "😶‍🌫️💔",
  "laughs to avoid crying": "😂😭",
  "shuts down emotionally": "📴❤️",
  "turns off brain": "🔌🧠",
};