/**
 * Emoji mappings for social media and technology expressions
 * This file contains mappings between text expressions and corresponding emojis
 * for social media behavior, phone activities, and digital life.
 */

export const socialMediaExpressions: Record<string, string> = {
  // Phone and social media actions
  "stares at phone": "📱👀",
  "checks phone": "📱👀",
  "checks notifications again": "📲👀",
  "scrolls endlessly": "📱🌀",
  "scrolls dead-eyed": "👁️📱",
  "scrolls for serotonin": "📱🧠",
  "refreshes feed": "🔄📲",
  "refreshes again": "🔁👀",
  "accidentally likes post": "😳❤️",
  "deletes comment quickly": "🫣🗑️",
  "creeps on profile": "🕵️‍♂️📸",
  "lurks in comments": "👀💬",
  "starts typing": "💬⌨️",
  "types then stops": "✍️⏸️",
  "leaves on read": "😐📱",
  "reads message instantly": "⚡📨",
  "sends too many emojis": "😂🔥💯😩😭",
  "updates status": "🗣️🆕",
  "changes pfp": "🧑‍🎨",
  "downloads meme": "🖼️😆",
  "reposts with caption": "🔁📝",
  "makes meme": "🎨🧠",
  "gets ratioed": "📉",
  "wins argument online": "🧠🏆",
  "loses debate": "😬💢",
  "posts hot take": "🔥🤔",
  "edits post quickly": "✍️💨",
  "deletes everything": "🧹🗑️",
  "starts new account": "🆕📱",
  "logs out dramatically": "👋📴",
  
  // Dating app expressions
  "swipes left": "👈❌",
  "swipes right": "👉💘",
  "gets a match": "💘🔁",
  "sends pickup line": "😏💬",
  "gets left on seen": "😔👀",
  "tries again anyway": "😤💬",
  "gets blocked": "🚫",
  "makes fake profile": "👻",
  "gets catfished": "🎣😨",
  "flirts badly": "😬💔",
  "tries being smooth": "😎😏",
  "fails miserably": "💀",
  
  // Digital communication
  "blames autocorrect": "😤🔤",
  "sends accidental text": "😱📱",
  "types entire paragraph": "🧠🧾",
  "writes essay": "📝📚",
  "reads messages, doesn't reply": "📬👀",
  "socially logs off": "📴😶",
  "thinks of texting them": "🤔📱",
  "doesn't": "❌💬",
  "gets left on read": "📨😐",
  "responds dryly": "✍️🧂",
  "ghosting": "👻",
  "ghosts everyone": "👻📴",
  "replies after 3 days": "📱🕒",
  "panics when phone rings": "📞😱",
  
  // Digital content creation
  "starts fanfic": "✍️✨",
  "adds cliffhanger": "😈📖",
  "cries over characters": "😭📚",
  "fangirls aggressively": "🥹👏",
  "ships them hard": "❤️‍🔥⛵",
  "draws fanart": "🖌️🎨",
  "gets featured": "🎉✨",
  "becomes mutuals": "🤝🫶",
  "forms online bond": "🌐❤️",
  "makes discord server": "🧃🎮",
  "posts in general chat": "💬👀",
  "mutes server": "🔕",
  "boosts server": "🚀",
  "joins voice chat": "🎧🔊",
  "forgets mic on": "😳🎤",
  "leaves VC awkwardly": "🏃🔇",
  
  // Gaming expressions
  "rages in game": "🎮😡",
  "throws controller": "🎮💥",
  "slams keyboard": "⌨️👊",
  "gets headshot": "💀🎯",
  "wins match": "🏆🔥",
  "gets MVP": "⭐💪",
  "camps corner": "🫥🔫",
  "rushes mid": "🏃🔫",
  "dies instantly": "💀",
  "top frags": "🔝🔫",
  "bottom frags": "🧍",
  "blames lag": "📶😠",
  "ping spikes": "📈📶",
  "dc's mid game": "🔌🎮",
  "reconnects miraculously": "😮🔁",
  "gets clutch win": "🤯🏆",
  "team throws": "😭👎",
  "calls GG": "✌️🎮",
  "queue dodges": "🏃❌",
  
  // Streaming and content creation
  "streams on twitch": "🎥💜",
  "gets one viewer": "👁️",
  "talks to self on stream": "🗣️📺",
  "gets raided": "🚪👥",
  "mod bans troll": "🔨🙅",
  "chat spams pog": "🗨️🔥",
  "drops emotes": "😎🎉",
  "hits sub goal": "🎉🎯",
  "starts giveaway": "🎁🎊",
  "forgets camera on": "😳📷",
  "mic peaks": "🔊😩",
  "gets clip of the day": "✂️📽️",
  "uploads highlight": "🌟🎞️",
  "posts to YouTube": "▶️📹",
  "edits thumbnail": "🖼️✨",
  "clickbaits hard": "🪝😆",
  "gets views": "👀🔥",
  "reads comments": "💬📱",
  "regrets immediately": "😐🔙",
  "turns off replies": "🚫💬",
  "posts 'no hate pls'": "🥲💬",
  "deletes video": "🗑️📹",
  "takes break from social": "😶📵",
  "posts return video": "📹🔁",
  "fans go wild": "🥳👏",
  "haters still mad": "😤💢",
  "announces merch": "👕🛒",
  "sells out instantly": "💸🔥",
  "makes limited drop": "⏳🎁",
  "rebrands": "🆕🎨",
  "changes username": "✏️📛",
  "starts podcast": "🎙️🧠",
  "records first ep": "📼🎧",
  
  // Digital life struggles
  "forgets password": "🔒❌",
  "resets password again": "♻️🔐",
  "creates worse one": "🤡🆕",
  "accidentally opens front cam": "📱😳",
  "accidentally opens camera again": "📸😵",
  "uses phone as mirror": "📱🪞",
  "buys stuff online again": "🛒💸",
  "tracks package obsessively": "📦👀",
  "forgets what was ordered": "🤔📦",
  "adds to wishlist": "💭🛍️",
  "can't find charger": "🔌❌",
  "gets tangled in headphones": "🎧🪢",
  "phone storage full": "💾🔴",
  "deletes old photos": "📸🗑️",
  "downloads 5 new apps": "📲🆕",
  "uses none": "❌📱",
};