/**
 * Emoji mappings for special actions and activities
 * This file contains mappings between text expressions and corresponding emojis
 * for special actions, activities, and other miscellaneous expressions.
 */

export const specialActions: Record<string, string> = {
  // Digital actions
  "takes pic": "📸",
  "takes photo": "📸",
  "snaps selfie": "🤳",
  "snaps photo": "📸",
  "screenshots": "📸",
  "saves pic": "💾",
  "records video": "🎥",
  "starts livestream": "📡",
  "zooms in": "🔍",
  "zooms out": "🔭",
  "enhances image": "🕵️‍♂️",
  "types quickly": "⌨️",
  "types nervously": "🧑‍💻",
  "spams keyboard": "🧑‍💻",
  "slams keys": "😤⌨️",
  "spams emojis": "😍😎😂🔥",
  "sends text": "📱",
  "deletes message": "❌",
  "unsends": "⏪",
  "double texts": "📱📱",
  "refreshes chat": "🔁",
  "posts meme": "🐸",
  "shares gif": "🎞️",
  "reacts with emoji": "😆👍❤️",
  "spams reactions": "🔥🔥🔥",
  
  // Digital states
  "ghosts": "👻",
  "ghosts conversation": "👻",
  "gets left on seen": "😭",
  "left on read": "🥲",
  "waits for reply": "⏳",
  "blocks user": "🚫",
  "unfollows": "❌",
  "deletes message chain": "🧹",
  "burns evidence": "🔥",
  "erases board": "🧽",
  "clears chat": "🧼",
  
  // Technological actions
  "shuts laptop": "💻✖️",
  "disconnects internet": "📶❌",
  "powers off phone": "📴",
  "slaps phone away": "📱💥",
  "turns off notifications": "🔕",
  "puts phone face down": "🙃",
  "locks screen": "🔒",
  "enables do not disturb": "🛑",
  "throws phone": "📱💥",
  "slams laptop shut": "💻",
  "computer crashes": "💻💥",
  "system reboots": "🔄💻",
  "reboots": "🔁",
  "glitches": "🖥️",
  "404s": "❌",
  "malfunctions": "⚠️",
  "alerts": "🚨",
  "files disappear": "🫥📁",
  "downloads shady file": "😬💾",
  
  // Communication
  "whispers": "🤫",
  "whispers secrets": "🤫",
  "mutters": "🤐",
  "mutters under breath": "😤",
  "mumbles": "😶",
  "yells": "🗣️",
  "shouts": "📣",
  "announces": "📢",
  "explains quickly": "💬",
  "talks fast": "😮‍💨",
  "talks too much": "😅",
  "talks over others": "😬",
  "gets interrupted": "😑",
  "gets cut off": "✂️",
  "tells joke": "😄",
  "makes pun": "😏",
  "groans at pun": "😩",
  "breaks fourth wall": "🪞",
  "narrates": "📖",
  "narrates dramatically": "🎬",
  "monologues": "🎙️",
  "commentates": "🎤",
  "voice cracks": "🫨",
  "clears throat": "😬",
  "talks to self": "🧠💬",
  "eavesdrops": "👂",
  
  // Entertainment actions
  "breaks into song": "🎤🎶",
  "starts beatboxing": "🥁",
  "plays air guitar": "🎸",
  "plays air drums": "🥁",
  "starts dancing": "💃",
  "celebrates": "🎉",
  "throws confetti": "🎊",
  "pops champagne": "🍾",
  "makes toast": "🥂",
  "raises glass": "🍷",
  "clinks glasses": "🥂",
  "starts party": "🪩",
  "turns up volume": "🔊",
  "blasts music": "🔥🎶",
  "cheers": "🎉",
  
  // Fantasy/RPG actions
  "casts spell": "✨🧙",
  "uses potion": "🧪",
  "heals": "💖",
  "revives": "💫",
  "resurrects": "✝️",
  "casts fireball": "🔥",
  "uses shield": "🛡️",
  "draws sword": "⚔️",
  "aims bow": "🏹",
  "throws grenade": "💣",
  "summons": "👻",
  "levels up": "🆙",
  "wins": "🏆",
  "loses": "😞",
  "quits": "🏳️",
  "surrenders": "🙇",
  "retreats": "🏃",
  "attacks": "🗡️",
  "defends": "🛡️",
  
  // Sleep and rest
  "falls asleep": "😴",
  "sleeps": "😴",
  "snores": "💤",
  "snores loudly": "💤",
  "dreams": "💭",
  "dreams vividly": "💭🌈",
  "has nightmare": "😱",
  "wakes up": "😳",
  "wakes up suddenly": "😳",
  "pretends to sleep": "🫣",
  "covers face with pillow": "😩🛏️",
  "hides under blanket": "😴🛌",
  "lays down": "🛌",
  
  // Miscellaneous actions
  "grovels": "🙇",
  "pleads": "🥺",
  "begs": "🙏",
  "prays": "🙏",
  "meditates": "🧘",
  "flips table": "(╯°□°）╯︵ ┻━┻",
  "throws something": "💢",
  "slams door": "🚪",
  "slams door behind": "🚪💥",
  "locks door": "🔒",
  "faceplants": "🤕",
  "bangs head on desk": "😫",
  "bangs head against wall": "😩",
  "makes coffee": "☕",
  "spills coffee": "☕💥",
  "burns tongue": "🔥👅",
  "rushes out door": "🏃‍♂️🚪",
  "misses bus": "🚌💨",
  "runs late": "⏰😱",
  "curses under breath": "🤬",
  "scribbles angrily": "✍️😠",
  "writes quickly": "✍️",
  "doodles": "✏️🎨",
  "zones out in class": "😴",
  "passes note": "📝👀",
  "leaves note behind": "📝",
  "scribbles": "📝",
  "draws heart": "❤️",
  "writes love letter": "💌",
};